// Code is generated by script; DO NOT EDIT.

package data

var ar_Locale = LocaleData{
	Name:      "ar",
	DateOrder: "DMY",
	SkipWords: []string{"'", ",", "-", ".", "/", ";", "@", "[", "]", "|", "الساعة", "في", "مساءً", "هـ"},
	Translations: map[string]string{
		`يناير`:            "january",
		`فبراير`:           "february",
		`مارس`:             "march",
		`أبريل`:            "april",
		`مايو`:             "may",
		`يونيو`:            "june",
		`يوليو`:            "july",
		`أغسطس`:            "august",
		`سبتمبر`:           "september",
		`أكتوبر`:           "october",
		`نوفمبر`:           "november",
		`ديسمبر`:           "december",
		`الاثنين`:          "monday",
		`الثلاثاء`:         "tuesday",
		`الأربعاء`:         "wednesday",
		`الخميس`:           "thursday",
		`الجمعة`:           "friday",
		`السبت`:            "saturday",
		`الأحد`:            "sunday",
		`ص`:                "am",
		`صباحًا`:           "am",
		`م`:                "pm",
		`مساءً`:            "pm",
		`السنة`:            "year",
		`الشهر`:            "month",
		`الأسبوع`:          "week",
		`يوم`:              "day",
		`الساعات`:          "hour",
		`الثواني`:          "second",
		`السنة الماضية`:    "1 year ago",
		`السنة الحالية`:    "0 year ago",
		`السنة القادمة`:    "in 1 year",
		`الشهر الماضي`:     "1 month ago",
		`هذا الشهر`:        "0 month ago",
		`الشهر القادم`:     "in 1 month",
		`الأسبوع الماضي`:   "1 week ago",
		`هذا الأسبوع`:      "0 week ago",
		`الأسبوع القادم`:   "in 1 week",
		`أمس`:              "1 day ago",
		`اليوم`:            "0 day ago",
		`غدًا`:             "in 1 day",
		`الساعة الحالية`:   "0 hour ago",
		`هذه الدقيقة`:      "0 minute ago",
		`الآن`:             "0 second ago",
		`خلال (\d+) سنة`:   "in $1 year",
		`قبل (\d+) سنة`:    "$1 year ago",
		`خلال (\d+) شهر`:   "in $1 month",
		`قبل (\d+) شهر`:    "$1 month ago",
		`خلال (\d+) أسبوع`: "in $1 week",
		`قبل (\d+) أسبوع`:  "$1 week ago",
		`خلال (\d+) يوم`:   "in $1 day",
		`قبل (\d+) يوم`:    "$1 day ago",
		`خلال (\d+) ساعة`:  "in $1 hour",
		`قبل (\d+) ساعة`:   "$1 hour ago",
		`خلال (\d+) دقيقة`: "in $1 minute",
		`خلال (\d+) ثانية`: "in $1 second",
		`قبل (\d+) ثانية`:  "$1 second ago",
		`الإثنين`:          "monday",
		`صباحاً`:           "am",
		`عام`:              "year",
		`سنة`:              "year",
		`شهر`:              "month",
		`أسبوع`:            "week",
		`أيام`:             "day",
		`ساعة`:             "hour",
		`ساعات`:            "hour",
		`دقيقة`:            "minute",
		`دقائق`:            "minute",
		`ثانية`:            "second",
		`خلال`:             "in",
		`منذ`:              "ago",
		`اليوم السابق`:     "1 day ago",
		`الأمس`:            "1 day ago",
		`يومين`:            "2 day",
		`ساعتين`:           "2 hour",
		`ساعة واحدة`:       "1 hour ago",
	},
}

var ar_AE_Locale = LocaleData{
	Name:      "ar-AE",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`هذه السنة`:     "0 year ago",
		`السنة التالية`: "in 1 year",
	},
}

var ar_BH_Locale = LocaleData{
	Name:      "ar-BH",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_DJ_Locale = LocaleData{
	Name:      "ar-DJ",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_DZ_Locale = LocaleData{
	Name:      "ar-DZ",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`جانفي`:  "january",
		`فيفري`:  "february",
		`أفريل`:  "april",
		`ماي`:    "may",
		`جوان`:   "june",
		`جويلية`: "july",
		`أوت`:    "august",
	},
}

var ar_EG_Locale = LocaleData{
	Name:      "ar-EG",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_EH_Locale = LocaleData{
	Name:      "ar-EH",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_ER_Locale = LocaleData{
	Name:      "ar-ER",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_IL_Locale = LocaleData{
	Name:      "ar-IL",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_IQ_Locale = LocaleData{
	Name:      "ar-IQ",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`كانون الثاني`: "january",
		`شباط`:         "february",
		`آذار`:         "march",
		`نيسان`:        "april",
		`أيار`:         "may",
		`حزيران`:       "june",
		`تموز`:         "july",
		`آب`:           "august",
		`أيلول`:        "september",
		`تشرين الأول`:  "october",
		`تشرین الأول`:  "october",
		`تشرين الثاني`: "november",
		`كانون الأول`:  "december",
	},
}

var ar_JO_Locale = LocaleData{
	Name:      "ar-JO",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`كانون الثاني`: "january",
		`شباط`:         "february",
		`آذار`:         "march",
		`نيسان`:        "april",
		`أيار`:         "may",
		`حزيران`:       "june",
		`تموز`:         "july",
		`آب`:           "august",
		`أيلول`:        "september",
		`تشرين الأول`:  "october",
		`تشرين الثاني`: "november",
		`كانون الأول`:  "december",
	},
}

var ar_KM_Locale = LocaleData{
	Name:      "ar-KM",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_KW_Locale = LocaleData{
	Name:      "ar-KW",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_LB_Locale = LocaleData{
	Name:      "ar-LB",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`كانون الثاني`: "january",
		`شباط`:         "february",
		`آذار`:         "march",
		`نيسان`:        "april",
		`أيار`:         "may",
		`حزيران`:       "june",
		`تموز`:         "july",
		`آب`:           "august",
		`أيلول`:        "september",
		`تشرين الأول`:  "october",
		`تشرين الثاني`: "november",
		`كانون الأول`:  "december",
	},
}

var ar_LY_Locale = LocaleData{
	Name:      "ar-LY",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_MA_Locale = LocaleData{
	Name:      "ar-MA",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`ماي`:    "may",
		`يوليوز`: "july",
		`غشت`:    "august",
		`شتنبر`:  "september",
		`نونبر`:  "november",
		`دجنبر`:  "december",
	},
}

var ar_MR_Locale = LocaleData{
	Name:      "ar-MR",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`إبريل`: "april",
		`أغشت`:  "august",
		`شتمبر`: "september",
		`دجمبر`: "december",
	},
}

var ar_OM_Locale = LocaleData{
	Name:      "ar-OM",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_PS_Locale = LocaleData{
	Name:      "ar-PS",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`كانون الثاني`: "january",
		`شباط`:         "february",
		`آذار`:         "march",
		`نيسان`:        "april",
		`أيار`:         "may",
		`حزيران`:       "june",
		`تموز`:         "july",
		`آب`:           "august",
		`أيلول`:        "september",
		`تشرين الأول`:  "october",
		`تشرين الثاني`: "november",
		`كانون الأول`:  "december",
	},
}

var ar_QA_Locale = LocaleData{
	Name:      "ar-QA",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_SA_Locale = LocaleData{
	Name:      "ar-SA",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_SD_Locale = LocaleData{
	Name:      "ar-SD",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_SO_Locale = LocaleData{
	Name:      "ar-SO",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_SS_Locale = LocaleData{
	Name:      "ar-SS",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_SY_Locale = LocaleData{
	Name:      "ar-SY",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`كانون الثاني`: "january",
		`شباط`:         "february",
		`آذار`:         "march",
		`نيسان`:        "april",
		`أيار`:         "may",
		`حزيران`:       "june",
		`تموز`:         "july",
		`آب`:           "august",
		`أيلول`:        "september",
		`تشرين الأول`:  "october",
		`تشرين الثاني`: "november",
		`كانون الأول`:  "december",
	},
}

var ar_TD_Locale = LocaleData{
	Name:      "ar-TD",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}

var ar_TN_Locale = LocaleData{
	Name:      "ar-TN",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`جانفي`:  "january",
		`فيفري`:  "february",
		`أفريل`:  "april",
		`ماي`:    "may",
		`جوان`:   "june",
		`جويلية`: "july",
		`أوت`:    "august",
	},
}

var ar_YE_Locale = LocaleData{
	Name:      "ar-YE",
	Parent:    &ar_Locale,
	DateOrder: "DMY",
}
