// Code is generated by script; DO NOT EDIT.

package data

import "regexp"

var en_Locale = LocaleData{
	Name:         "en",
	DateOrder:    "MDY",
	SkipWords:    []string{"'", ",", "-", ".", "/", ";", "@", "[", "]", "about", "ad", "and", "at", "by", "just", "m", "nd", "of", "on", "rd", "st", "th", "the", "|"},
	PertainWords: []string{"of"},
	Simplifications: map[*regexp.Regexp]string{
		regexp.MustCompile(`(\A|\W|_)(?:12\s+)?midnight(\z|\W|_)`):     "${1}00:00${2}",
		regexp.MustCompile(`(\A|\W|_)(?:12\s+)?noon(\z|\W|_)`):         "${1}12:00${2}",
		regexp.MustCompile(`(\A|\W|_)(\d+)h(\d+)m?(\z|\W|_)`):          "${1}${2}:${3}${4}",
		regexp.MustCompile(`(\A|\W|_)(from\s+)now(\z|\W|_)`):           "${1}${2}in${3}",
		regexp.MustCompile(`(\A|\W|_)a(\z|\W|_)`):                      "${1}1${2}",
		regexp.MustCompile(`(\A|\W|_)an(\z|\W|_)`):                     "${1}1${2}",
		regexp.MustCompile(`(\A|\W|_)eight(\z|\W|_)`):                  "${1}8${2}",
		regexp.MustCompile(`(\A|\W|_)eleven(\z|\W|_)`):                 "${1}11${2}",
		regexp.MustCompile(`(\A|\W|_)five(\z|\W|_)`):                   "${1}5${2}",
		regexp.MustCompile(`(\A|\W|_)four(\z|\W|_)`):                   "${1}4${2}",
		regexp.MustCompile(`(\A|\W|_)less than 1 minute ago(\z|\W|_)`): "${1}45 second ago${2}",
		regexp.MustCompile(`(\A|\W|_)nine(\z|\W|_)`):                   "${1}9${2}",
		regexp.MustCompile(`(\A|\W|_)one(\z|\W|_)`):                    "${1}1${2}",
		regexp.MustCompile(`(\A|\W|_)seven(\z|\W|_)`):                  "${1}7${2}",
		regexp.MustCompile(`(\A|\W|_)six(\z|\W|_)`):                    "${1}6${2}",
		regexp.MustCompile(`(\A|\W|_)ten(\z|\W|_)`):                    "${1}10${2}",
		regexp.MustCompile(`(\A|\W|_)three(\z|\W|_)`):                  "${1}3${2}",
		regexp.MustCompile(`(\A|\W|_)twelve(\z|\W|_)`):                 "${1}12${2}",
		regexp.MustCompile(`(\A|\W|_)two(\z|\W|_)`):                    "${1}2${2}",
	},
	Translations: []TranslationData{
		{regexp.MustCompile(`(\A|\W|_)day before yesterday(\z|\W|_)`), "${1}2 day ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) decades? ago(\z|\W|_)`), "${1}${2} decade ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) seconds ago(\z|\W|_)`), "${1}${2} second ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) decades?(\z|\W|_)`), "${1}in ${2} decade${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) months ago(\z|\W|_)`), "${1}${2} month ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) second ago(\z|\W|_)`), "${1}${2} second ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) minutes(\z|\W|_)`), "${1}in ${2} minute${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) seconds(\z|\W|_)`), "${1}in ${2} second${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) hours ago(\z|\W|_)`), "${1}${2} hour ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) month ago(\z|\W|_)`), "${1}${2} month ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) weeks ago(\z|\W|_)`), "${1}${2} week ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) years ago(\z|\W|_)`), "${1}${2} year ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) minute(\z|\W|_)`), "${1}in ${2} minute${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) months(\z|\W|_)`), "${1}in ${2} month${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) second(\z|\W|_)`), "${1}in ${2} second${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) days ago(\z|\W|_)`), "${1}${2} day ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) hour ago(\z|\W|_)`), "${1}${2} hour ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) week ago(\z|\W|_)`), "${1}${2} week ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) year ago(\z|\W|_)`), "${1}${2} year ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) hours(\z|\W|_)`), "${1}in ${2} hour${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) month(\z|\W|_)`), "${1}in ${2} month${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) weeks(\z|\W|_)`), "${1}in ${2} week${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) years(\z|\W|_)`), "${1}in ${2} year${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) day ago(\z|\W|_)`), "${1}${2} day ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) sec ago(\z|\W|_)`), "${1}${2} second ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) days(\z|\W|_)`), "${1}in ${2} day${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) hour(\z|\W|_)`), "${1}in ${2} hour${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) week(\z|\W|_)`), "${1}in ${2} week${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) year(\z|\W|_)`), "${1}in ${2} year${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) hr ago(\z|\W|_)`), "${1}${2} hour ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) mo ago(\z|\W|_)`), "${1}${2} month ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) wk ago(\z|\W|_)`), "${1}${2} week ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) yr ago(\z|\W|_)`), "${1}${2} year ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) day(\z|\W|_)`), "${1}in ${2} day${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) min(\z|\W|_)`), "${1}in ${2} minute${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) sec(\z|\W|_)`), "${1}in ${2} second${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) hr(\z|\W|_)`), "${1}in ${2} hour${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) mo(\z|\W|_)`), "${1}in ${2} month${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) wk(\z|\W|_)`), "${1}in ${2} week${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) yr(\z|\W|_)`), "${1}in ${2} year${3}"},
		{regexp.MustCompile(`(\A|\W|_)last decade(\z|\W|_)`), "${1}1 decade ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)next decade(\z|\W|_)`), "${1}in 1 decade${2}"},
		{regexp.MustCompile(`(\A|\W|_)this decade(\z|\W|_)`), "${1}1 decade ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)this minute(\z|\W|_)`), "${1}0 minute ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)last month(\z|\W|_)`), "${1}1 month ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)next month(\z|\W|_)`), "${1}in 1 month${2}"},
		{regexp.MustCompile(`(\A|\W|_)this month(\z|\W|_)`), "${1}0 month ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)last week(\z|\W|_)`), "${1}1 week ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)last year(\z|\W|_)`), "${1}1 year ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)next week(\z|\W|_)`), "${1}in 1 week${2}"},
		{regexp.MustCompile(`(\A|\W|_)next year(\z|\W|_)`), "${1}in 1 year${2}"},
		{regexp.MustCompile(`(\A|\W|_)september(\z|\W|_)`), "${1}september${2}"},
		{regexp.MustCompile(`(\A|\W|_)this hour(\z|\W|_)`), "${1}0 hour ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)this week(\z|\W|_)`), "${1}0 week ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)this year(\z|\W|_)`), "${1}0 year ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)wednesday(\z|\W|_)`), "${1}wednesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)yesterday(\z|\W|_)`), "${1}1 day ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)december(\z|\W|_)`), "${1}december${2}"},
		{regexp.MustCompile(`(\A|\W|_)february(\z|\W|_)`), "${1}february${2}"},
		{regexp.MustCompile(`(\A|\W|_)from now(\z|\W|_)`), "${1}in${2}"},
		{regexp.MustCompile(`(\A|\W|_)november(\z|\W|_)`), "${1}november${2}"},
		{regexp.MustCompile(`(\A|\W|_)saturday(\z|\W|_)`), "${1}saturday${2}"},
		{regexp.MustCompile(`(\A|\W|_)thursday(\z|\W|_)`), "${1}thursday${2}"},
		{regexp.MustCompile(`(\A|\W|_)tomorrow(\z|\W|_)`), "${1}in 1 day${2}"},
		{regexp.MustCompile(`(\A|\W|_)decades(\z|\W|_)`), "${1}decade${2}"},
		{regexp.MustCompile(`(\A|\W|_)january(\z|\W|_)`), "${1}january${2}"},
		{regexp.MustCompile(`(\A|\W|_)last mo(\z|\W|_)`), "${1}1 month ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)last wk(\z|\W|_)`), "${1}1 week ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)last yr(\z|\W|_)`), "${1}1 year ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)minutes(\z|\W|_)`), "${1}minute${2}"},
		{regexp.MustCompile(`(\A|\W|_)next mo(\z|\W|_)`), "${1}in 1 month${2}"},
		{regexp.MustCompile(`(\A|\W|_)next wk(\z|\W|_)`), "${1}in 1 week${2}"},
		{regexp.MustCompile(`(\A|\W|_)next yr(\z|\W|_)`), "${1}in 1 year${2}"},
		{regexp.MustCompile(`(\A|\W|_)october(\z|\W|_)`), "${1}october${2}"},
		{regexp.MustCompile(`(\A|\W|_)seconds(\z|\W|_)`), "${1}second${2}"},
		{regexp.MustCompile(`(\A|\W|_)this mo(\z|\W|_)`), "${1}0 month ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)this wk(\z|\W|_)`), "${1}0 week ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)this yr(\z|\W|_)`), "${1}0 year ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)tuesday(\z|\W|_)`), "${1}tuesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)august(\z|\W|_)`), "${1}august${2}"},
		{regexp.MustCompile(`(\A|\W|_)decade(\z|\W|_)`), "${1}decade${2}"},
		{regexp.MustCompile(`(\A|\W|_)friday(\z|\W|_)`), "${1}friday${2}"},
		{regexp.MustCompile(`(\A|\W|_)monday(\z|\W|_)`), "${1}monday${2}"},
		{regexp.MustCompile(`(\A|\W|_)months(\z|\W|_)`), "${1}month${2}"},
		{regexp.MustCompile(`(\A|\W|_)second(\z|\W|_)`), "${1}second${2}"},
		{regexp.MustCompile(`(\A|\W|_)sunday(\z|\W|_)`), "${1}sunday${2}"},
		{regexp.MustCompile(`(\A|\W|_)april(\z|\W|_)`), "${1}april${2}"},
		{regexp.MustCompile(`(\A|\W|_)hours(\z|\W|_)`), "${1}hour${2}"},
		{regexp.MustCompile(`(\A|\W|_)march(\z|\W|_)`), "${1}march${2}"},
		{regexp.MustCompile(`(\A|\W|_)month(\z|\W|_)`), "${1}month${2}"},
		{regexp.MustCompile(`(\A|\W|_)today(\z|\W|_)`), "${1}0 day ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)weeks(\z|\W|_)`), "${1}week${2}"},
		{regexp.MustCompile(`(\A|\W|_)years(\z|\W|_)`), "${1}year${2}"},
		{regexp.MustCompile(`(\A|\W|_)days(\z|\W|_)`), "${1}day${2}"},
		{regexp.MustCompile(`(\A|\W|_)hour(\z|\W|_)`), "${1}hour${2}"},
		{regexp.MustCompile(`(\A|\W|_)july(\z|\W|_)`), "${1}july${2}"},
		{regexp.MustCompile(`(\A|\W|_)june(\z|\W|_)`), "${1}june${2}"},
		{regexp.MustCompile(`(\A|\W|_)mins(\z|\W|_)`), "${1}minute${2}"},
		{regexp.MustCompile(`(\A|\W|_)secs(\z|\W|_)`), "${1}second${2}"},
		{regexp.MustCompile(`(\A|\W|_)sept(\z|\W|_)`), "${1}september${2}"},
		{regexp.MustCompile(`(\A|\W|_)tues(\z|\W|_)`), "${1}tuesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)week(\z|\W|_)`), "${1}week${2}"},
		{regexp.MustCompile(`(\A|\W|_)year(\z|\W|_)`), "${1}year${2}"},
		{regexp.MustCompile(`(\A|\W|_)ago(\z|\W|_)`), "${1}ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)apr(\z|\W|_)`), "${1}april${2}"},
		{regexp.MustCompile(`(\A|\W|_)aug(\z|\W|_)`), "${1}august${2}"},
		{regexp.MustCompile(`(\A|\W|_)day(\z|\W|_)`), "${1}day${2}"},
		{regexp.MustCompile(`(\A|\W|_)dec(\z|\W|_)`), "${1}december${2}"},
		{regexp.MustCompile(`(\A|\W|_)feb(\z|\W|_)`), "${1}february${2}"},
		{regexp.MustCompile(`(\A|\W|_)fri(\z|\W|_)`), "${1}friday${2}"},
		{regexp.MustCompile(`(\A|\W|_)hrs(\z|\W|_)`), "${1}hour${2}"},
		{regexp.MustCompile(`(\A|\W|_)jan(\z|\W|_)`), "${1}january${2}"},
		{regexp.MustCompile(`(\A|\W|_)jul(\z|\W|_)`), "${1}july${2}"},
		{regexp.MustCompile(`(\A|\W|_)jun(\z|\W|_)`), "${1}june${2}"},
		{regexp.MustCompile(`(\A|\W|_)mar(\z|\W|_)`), "${1}march${2}"},
		{regexp.MustCompile(`(\A|\W|_)may(\z|\W|_)`), "${1}may${2}"},
		{regexp.MustCompile(`(\A|\W|_)mon(\z|\W|_)`), "${1}monday${2}"},
		{regexp.MustCompile(`(\A|\W|_)nov(\z|\W|_)`), "${1}november${2}"},
		{regexp.MustCompile(`(\A|\W|_)now(\z|\W|_)`), "${1}0 second ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)oct(\z|\W|_)`), "${1}october${2}"},
		{regexp.MustCompile(`(\A|\W|_)sat(\z|\W|_)`), "${1}saturday${2}"},
		{regexp.MustCompile(`(\A|\W|_)sec(\z|\W|_)`), "${1}second${2}"},
		{regexp.MustCompile(`(\A|\W|_)sep(\z|\W|_)`), "${1}september${2}"},
		{regexp.MustCompile(`(\A|\W|_)sun(\z|\W|_)`), "${1}sunday${2}"},
		{regexp.MustCompile(`(\A|\W|_)thu(\z|\W|_)`), "${1}thursday${2}"},
		{regexp.MustCompile(`(\A|\W|_)tue(\z|\W|_)`), "${1}tuesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)wed(\z|\W|_)`), "${1}wednesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)am(\z|\W|_)`), "${1}am${2}"},
		{regexp.MustCompile(`(\A|\W|_)hr(\z|\W|_)`), "${1}hour${2}"},
		{regexp.MustCompile(`(\A|\W|_)in(\z|\W|_)`), "${1}in${2}"},
		{regexp.MustCompile(`(\A|\W|_)mo(\z|\W|_)`), "${1}month${2}"},
		{regexp.MustCompile(`(\A|\W|_)pm(\z|\W|_)`), "${1}pm${2}"},
		{regexp.MustCompile(`(\A|\W|_)wk(\z|\W|_)`), "${1}week${2}"},
		{regexp.MustCompile(`(\A|\W|_)yr(\z|\W|_)`), "${1}year${2}"},
		{regexp.MustCompile(`(\A|\W|_)h(\z|\W|_)`), "${1}hour${2}"},
		{regexp.MustCompile(`(\A|\W|_)m(\z|\W|_)`), "${1}minute${2}"},
		{regexp.MustCompile(`(\A|\W|_)s(\z|\W|_)`), "${1}second${2}"},
	},
}

var en_001_Locale = LocaleData{
	Name:      "en-001",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_150_Locale = LocaleData{
	Name:      "en-150",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_AG_Locale = LocaleData{
	Name:      "en-AG",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_AI_Locale = LocaleData{
	Name:      "en-AI",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_AS_Locale = LocaleData{
	Name:      "en-AS",
	Parent:    &en_Locale,
	DateOrder: "MDY",
}

var en_AT_Locale = LocaleData{
	Name:      "en-AT",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_AU_Locale = LocaleData{
	Name:      "en-AU",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_BB_Locale = LocaleData{
	Name:      "en-BB",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_BE_Locale = LocaleData{
	Name:      "en-BE",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_BI_Locale = LocaleData{
	Name:      "en-BI",
	Parent:    &en_Locale,
	DateOrder: "MDY",
}

var en_BM_Locale = LocaleData{
	Name:      "en-BM",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_BS_Locale = LocaleData{
	Name:      "en-BS",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_BW_Locale = LocaleData{
	Name:      "en-BW",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_BZ_Locale = LocaleData{
	Name:      "en-BZ",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_CA_Locale = LocaleData{
	Name:      "en-CA",
	Parent:    &en_Locale,
	DateOrder: "YMD",
	Translations: []TranslationData{
		{regexp.MustCompile(`(\A|\W|_)(\d+) secs ago(\z|\W|_)`), "${1}${2} second ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) hrs ago(\z|\W|_)`), "${1}${2} hour ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) mos ago(\z|\W|_)`), "${1}${2} month ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) wks ago(\z|\W|_)`), "${1}${2} week ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)(\d+) yrs ago(\z|\W|_)`), "${1}${2} year ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) mins(\z|\W|_)`), "${1}in ${2} minute${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) secs(\z|\W|_)`), "${1}in ${2} second${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) hrs(\z|\W|_)`), "${1}in ${2} hour${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) mos(\z|\W|_)`), "${1}in ${2} month${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) wks(\z|\W|_)`), "${1}in ${2} week${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) yrs(\z|\W|_)`), "${1}in ${2} year${3}"},
	},
}

var en_CC_Locale = LocaleData{
	Name:      "en-CC",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_CH_Locale = LocaleData{
	Name:      "en-CH",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_CK_Locale = LocaleData{
	Name:      "en-CK",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_CM_Locale = LocaleData{
	Name:      "en-CM",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_CX_Locale = LocaleData{
	Name:      "en-CX",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_CY_Locale = LocaleData{
	Name:      "en-CY",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_DE_Locale = LocaleData{
	Name:      "en-DE",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_DG_Locale = LocaleData{
	Name:      "en-DG",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_DK_Locale = LocaleData{
	Name:      "en-DK",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_DM_Locale = LocaleData{
	Name:      "en-DM",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_ER_Locale = LocaleData{
	Name:      "en-ER",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_FI_Locale = LocaleData{
	Name:      "en-FI",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_FJ_Locale = LocaleData{
	Name:      "en-FJ",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_FK_Locale = LocaleData{
	Name:      "en-FK",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_FM_Locale = LocaleData{
	Name:      "en-FM",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_GB_Locale = LocaleData{
	Name:      "en-GB",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_GD_Locale = LocaleData{
	Name:      "en-GD",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_GG_Locale = LocaleData{
	Name:      "en-GG",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_GH_Locale = LocaleData{
	Name:      "en-GH",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_GI_Locale = LocaleData{
	Name:      "en-GI",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_GM_Locale = LocaleData{
	Name:      "en-GM",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_GU_Locale = LocaleData{
	Name:      "en-GU",
	Parent:    &en_Locale,
	DateOrder: "MDY",
}

var en_GY_Locale = LocaleData{
	Name:      "en-GY",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_HK_Locale = LocaleData{
	Name:      "en-HK",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_IE_Locale = LocaleData{
	Name:      "en-IE",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_IL_Locale = LocaleData{
	Name:      "en-IL",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_IM_Locale = LocaleData{
	Name:      "en-IM",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_IN_Locale = LocaleData{
	Name:      "en-IN",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_IO_Locale = LocaleData{
	Name:      "en-IO",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_JE_Locale = LocaleData{
	Name:      "en-JE",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_JM_Locale = LocaleData{
	Name:      "en-JM",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_KE_Locale = LocaleData{
	Name:      "en-KE",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_KI_Locale = LocaleData{
	Name:      "en-KI",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_KN_Locale = LocaleData{
	Name:      "en-KN",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_KY_Locale = LocaleData{
	Name:      "en-KY",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_LC_Locale = LocaleData{
	Name:      "en-LC",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_LR_Locale = LocaleData{
	Name:      "en-LR",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_LS_Locale = LocaleData{
	Name:      "en-LS",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_MG_Locale = LocaleData{
	Name:      "en-MG",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_MH_Locale = LocaleData{
	Name:      "en-MH",
	Parent:    &en_Locale,
	DateOrder: "MDY",
}

var en_MO_Locale = LocaleData{
	Name:      "en-MO",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_MP_Locale = LocaleData{
	Name:      "en-MP",
	Parent:    &en_Locale,
	DateOrder: "MDY",
}

var en_MS_Locale = LocaleData{
	Name:      "en-MS",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_MT_Locale = LocaleData{
	Name:      "en-MT",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_MU_Locale = LocaleData{
	Name:      "en-MU",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_MW_Locale = LocaleData{
	Name:      "en-MW",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_MY_Locale = LocaleData{
	Name:      "en-MY",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_NA_Locale = LocaleData{
	Name:      "en-NA",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_NF_Locale = LocaleData{
	Name:      "en-NF",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_NG_Locale = LocaleData{
	Name:      "en-NG",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_NL_Locale = LocaleData{
	Name:      "en-NL",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_NR_Locale = LocaleData{
	Name:      "en-NR",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_NU_Locale = LocaleData{
	Name:      "en-NU",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_NZ_Locale = LocaleData{
	Name:      "en-NZ",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_PG_Locale = LocaleData{
	Name:      "en-PG",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_PH_Locale = LocaleData{
	Name:      "en-PH",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_PK_Locale = LocaleData{
	Name:      "en-PK",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_PN_Locale = LocaleData{
	Name:      "en-PN",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_PR_Locale = LocaleData{
	Name:      "en-PR",
	Parent:    &en_Locale,
	DateOrder: "MDY",
}

var en_PW_Locale = LocaleData{
	Name:      "en-PW",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_RW_Locale = LocaleData{
	Name:      "en-RW",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_SB_Locale = LocaleData{
	Name:      "en-SB",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_SC_Locale = LocaleData{
	Name:      "en-SC",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_SD_Locale = LocaleData{
	Name:      "en-SD",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_SE_Locale = LocaleData{
	Name:      "en-SE",
	Parent:    &en_Locale,
	DateOrder: "YMD",
}

var en_SG_Locale = LocaleData{
	Name:      "en-SG",
	Parent:    &en_Locale,
	DateOrder: "DMY",
	Translations: []TranslationData{
		{regexp.MustCompile(`(\A|\W|_)(\d+) mth ago(\z|\W|_)`), "${1}${2} month ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)in (\d+) mth(\z|\W|_)`), "${1}in ${2} month${3}"},
		{regexp.MustCompile(`(\A|\W|_)last mth(\z|\W|_)`), "${1}1 month ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)next mth(\z|\W|_)`), "${1}in 1 month${2}"},
		{regexp.MustCompile(`(\A|\W|_)this mth(\z|\W|_)`), "${1}0 month ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)mth(\z|\W|_)`), "${1}month${2}"},
	},
}

var en_SH_Locale = LocaleData{
	Name:      "en-SH",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_SI_Locale = LocaleData{
	Name:      "en-SI",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_SL_Locale = LocaleData{
	Name:      "en-SL",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_SS_Locale = LocaleData{
	Name:      "en-SS",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_SX_Locale = LocaleData{
	Name:      "en-SX",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_SZ_Locale = LocaleData{
	Name:      "en-SZ",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_TC_Locale = LocaleData{
	Name:      "en-TC",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_TK_Locale = LocaleData{
	Name:      "en-TK",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_TO_Locale = LocaleData{
	Name:      "en-TO",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_TT_Locale = LocaleData{
	Name:      "en-TT",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_TV_Locale = LocaleData{
	Name:      "en-TV",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_TZ_Locale = LocaleData{
	Name:      "en-TZ",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_UG_Locale = LocaleData{
	Name:      "en-UG",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_UM_Locale = LocaleData{
	Name:      "en-UM",
	Parent:    &en_Locale,
	DateOrder: "MDY",
}

var en_VC_Locale = LocaleData{
	Name:      "en-VC",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_VG_Locale = LocaleData{
	Name:      "en-VG",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_VI_Locale = LocaleData{
	Name:      "en-VI",
	Parent:    &en_Locale,
	DateOrder: "MDY",
}

var en_VU_Locale = LocaleData{
	Name:      "en-VU",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_WS_Locale = LocaleData{
	Name:      "en-WS",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_ZA_Locale = LocaleData{
	Name:      "en-ZA",
	Parent:    &en_Locale,
	DateOrder: "YMD",
}

var en_ZM_Locale = LocaleData{
	Name:      "en-ZM",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}

var en_ZW_Locale = LocaleData{
	Name:      "en-ZW",
	Parent:    &en_Locale,
	DateOrder: "DMY",
}
