// Code is generated by script; DO NOT EDIT.

package data

var es_Locale = LocaleData{
	Name:         "es",
	DateOrder:    "DMY",
	SkipWords:    []string{"'", ",", "-", ".", "/", ";", "@", "[", "]", "a las", "cerca", "de", "del", "en", "y", "|"},
	PertainWords: []string{"de", "del"},
	Simplifications: map[string]string{
		`un`:  "1",
		`una`: "1",
	},
	Translations: map[string]string{
		`(\A|\W|_)enero(\z|\W|_)`:                    "${1}january${2}",
		`(\A|\W|_)ene(\z|\W|_)`:                      "${1}january${2}",
		`(\A|\W|_)febrero(\z|\W|_)`:                  "${1}february${2}",
		`(\A|\W|_)feb(\z|\W|_)`:                      "${1}february${2}",
		`(\A|\W|_)marzo(\z|\W|_)`:                    "${1}march${2}",
		`(\A|\W|_)mar(\z|\W|_)`:                      "${1}march${2}",
		`(\A|\W|_)abril(\z|\W|_)`:                    "${1}april${2}",
		`(\A|\W|_)abr(\z|\W|_)`:                      "${1}april${2}",
		`(\A|\W|_)mayo(\z|\W|_)`:                     "${1}may${2}",
		`(\A|\W|_)may(\z|\W|_)`:                      "${1}may${2}",
		`(\A|\W|_)junio(\z|\W|_)`:                    "${1}june${2}",
		`(\A|\W|_)jun(\z|\W|_)`:                      "${1}june${2}",
		`(\A|\W|_)julio(\z|\W|_)`:                    "${1}july${2}",
		`(\A|\W|_)jul(\z|\W|_)`:                      "${1}july${2}",
		`(\A|\W|_)agosto(\z|\W|_)`:                   "${1}august${2}",
		`(\A|\W|_)ago(\z|\W|_)`:                      "${1}august${2}",
		`(\A|\W|_)septiembre(\z|\W|_)`:               "${1}september${2}",
		`(\A|\W|_)sept(\z|\W|_)`:                     "${1}september${2}",
		`(\A|\W|_)octubre(\z|\W|_)`:                  "${1}october${2}",
		`(\A|\W|_)oct(\z|\W|_)`:                      "${1}october${2}",
		`(\A|\W|_)noviembre(\z|\W|_)`:                "${1}november${2}",
		`(\A|\W|_)nov(\z|\W|_)`:                      "${1}november${2}",
		`(\A|\W|_)diciembre(\z|\W|_)`:                "${1}december${2}",
		`(\A|\W|_)dic(\z|\W|_)`:                      "${1}december${2}",
		`(\A|\W|_)lunes(\z|\W|_)`:                    "${1}monday${2}",
		`(\A|\W|_)lun(\z|\W|_)`:                      "${1}monday${2}",
		`(\A|\W|_)martes(\z|\W|_)`:                   "${1}tuesday${2}",
		`(\A|\W|_)miércoles(\z|\W|_)`:                "${1}wednesday${2}",
		`(\A|\W|_)mié(\z|\W|_)`:                      "${1}wednesday${2}",
		`(\A|\W|_)jueves(\z|\W|_)`:                   "${1}thursday${2}",
		`(\A|\W|_)jue(\z|\W|_)`:                      "${1}thursday${2}",
		`(\A|\W|_)viernes(\z|\W|_)`:                  "${1}friday${2}",
		`(\A|\W|_)vie(\z|\W|_)`:                      "${1}friday${2}",
		`(\A|\W|_)sábado(\z|\W|_)`:                   "${1}saturday${2}",
		`(\A|\W|_)sáb(\z|\W|_)`:                      "${1}saturday${2}",
		`(\A|\W|_)domingo(\z|\W|_)`:                  "${1}sunday${2}",
		`(\A|\W|_)dom(\z|\W|_)`:                      "${1}sunday${2}",
		`(\A|\W|_)am(\z|\W|_)`:                       "${1}am${2}",
		`(\A|\W|_)pm(\z|\W|_)`:                       "${1}pm${2}",
		`(\A|\W|_)año(\z|\W|_)`:                      "${1}year${2}",
		`(\A|\W|_)a(\z|\W|_)`:                        "${1}year${2}",
		`(\A|\W|_)mes(\z|\W|_)`:                      "${1}month${2}",
		`(\A|\W|_)m(\z|\W|_)`:                        "${1}month${2}",
		`(\A|\W|_)semana(\z|\W|_)`:                   "${1}week${2}",
		`(\A|\W|_)sem(\z|\W|_)`:                      "${1}week${2}",
		`(\A|\W|_)día(\z|\W|_)`:                      "${1}day${2}",
		`(\A|\W|_)d(\z|\W|_)`:                        "${1}day${2}",
		`(\A|\W|_)hora(\z|\W|_)`:                     "${1}hour${2}",
		`(\A|\W|_)h(\z|\W|_)`:                        "${1}hour${2}",
		`(\A|\W|_)segundo(\z|\W|_)`:                  "${1}second${2}",
		`(\A|\W|_)s(\z|\W|_)`:                        "${1}second${2}",
		`(\A|\W|_)el año pasado(\z|\W|_)`:            "${1}1 year ago${2}",
		`(\A|\W|_)este año(\z|\W|_)`:                 "${1}0 year ago${2}",
		`(\A|\W|_)el próximo año(\z|\W|_)`:           "${1}in 1 year${2}",
		`(\A|\W|_)el mes pasado(\z|\W|_)`:            "${1}1 month ago${2}",
		`(\A|\W|_)este mes(\z|\W|_)`:                 "${1}0 month ago${2}",
		`(\A|\W|_)el próximo mes(\z|\W|_)`:           "${1}in 1 month${2}",
		`(\A|\W|_)la semana pasada(\z|\W|_)`:         "${1}1 week ago${2}",
		`(\A|\W|_)esta semana(\z|\W|_)`:              "${1}0 week ago${2}",
		`(\A|\W|_)la próxima semana(\z|\W|_)`:        "${1}in 1 week${2}",
		`(\A|\W|_)ayer(\z|\W|_)`:                     "${1}1 day ago${2}",
		`(\A|\W|_)hoy(\z|\W|_)`:                      "${1}0 day ago${2}",
		`(\A|\W|_)mañana(\z|\W|_)`:                   "${1}in 1 day${2}",
		`(\A|\W|_)esta hora(\z|\W|_)`:                "${1}0 hour ago${2}",
		`(\A|\W|_)este minuto(\z|\W|_)`:              "${1}0 minute ago${2}",
		`(\A|\W|_)ahora(\z|\W|_)`:                    "${1}0 second ago${2}",
		`(\A|\W|_)dentro de (\d+) año(\z|\W|_)`:      "${1}in $2 year${3}",
		`(\A|\W|_)dentro de (\d+) años(\z|\W|_)`:     "${1}in $2 year${3}",
		`(\A|\W|_)dentro de (\d+) a(\z|\W|_)`:        "${1}in $2 year${3}",
		`(\A|\W|_)hace (\d+) año(\z|\W|_)`:           "${1}$2 year ago${3}",
		`(\A|\W|_)hace (\d+) años(\z|\W|_)`:          "${1}$2 year ago${3}",
		`(\A|\W|_)hace (\d+) a(\z|\W|_)`:             "${1}$2 year ago${3}",
		`(\A|\W|_)dentro de (\d+) mes(\z|\W|_)`:      "${1}in $2 month${3}",
		`(\A|\W|_)dentro de (\d+) meses(\z|\W|_)`:    "${1}in $2 month${3}",
		`(\A|\W|_)dentro de (\d+) m(\z|\W|_)`:        "${1}in $2 month${3}",
		`(\A|\W|_)hace (\d+) mes(\z|\W|_)`:           "${1}$2 month ago${3}",
		`(\A|\W|_)hace (\d+) meses(\z|\W|_)`:         "${1}$2 month ago${3}",
		`(\A|\W|_)hace (\d+) m(\z|\W|_)`:             "${1}$2 month ago${3}",
		`(\A|\W|_)dentro de (\d+) semana(\z|\W|_)`:   "${1}in $2 week${3}",
		`(\A|\W|_)dentro de (\d+) semanas(\z|\W|_)`:  "${1}in $2 week${3}",
		`(\A|\W|_)dentro de (\d+) sem(\z|\W|_)`:      "${1}in $2 week${3}",
		`(\A|\W|_)hace (\d+) semana(\z|\W|_)`:        "${1}$2 week ago${3}",
		`(\A|\W|_)hace (\d+) semanas(\z|\W|_)`:       "${1}$2 week ago${3}",
		`(\A|\W|_)hace (\d+) sem(\z|\W|_)`:           "${1}$2 week ago${3}",
		`(\A|\W|_)dentro de (\d+) día(\z|\W|_)`:      "${1}in $2 day${3}",
		`(\A|\W|_)dentro de (\d+) días(\z|\W|_)`:     "${1}in $2 day${3}",
		`(\A|\W|_)hace (\d+) día(\z|\W|_)`:           "${1}$2 day ago${3}",
		`(\A|\W|_)hace (\d+) días(\z|\W|_)`:          "${1}$2 day ago${3}",
		`(\A|\W|_)dentro de (\d+) hora(\z|\W|_)`:     "${1}in $2 hour${3}",
		`(\A|\W|_)dentro de (\d+) horas(\z|\W|_)`:    "${1}in $2 hour${3}",
		`(\A|\W|_)dentro de (\d+) h(\z|\W|_)`:        "${1}in $2 hour${3}",
		`(\A|\W|_)hace (\d+) hora(\z|\W|_)`:          "${1}$2 hour ago${3}",
		`(\A|\W|_)hace (\d+) horas(\z|\W|_)`:         "${1}$2 hour ago${3}",
		`(\A|\W|_)hace (\d+) h(\z|\W|_)`:             "${1}$2 hour ago${3}",
		`(\A|\W|_)dentro de (\d+) minuto(\z|\W|_)`:   "${1}in $2 minute${3}",
		`(\A|\W|_)dentro de (\d+) minutos(\z|\W|_)`:  "${1}in $2 minute${3}",
		`(\A|\W|_)dentro de (\d+) min(\z|\W|_)`:      "${1}in $2 minute${3}",
		`(\A|\W|_)dentro de (\d+) segundo(\z|\W|_)`:  "${1}in $2 second${3}",
		`(\A|\W|_)dentro de (\d+) segundos(\z|\W|_)`: "${1}in $2 second${3}",
		`(\A|\W|_)dentro de (\d+) s(\z|\W|_)`:        "${1}in $2 second${3}",
		`(\A|\W|_)hace (\d+) segundo(\z|\W|_)`:       "${1}$2 second ago${3}",
		`(\A|\W|_)hace (\d+) segundos(\z|\W|_)`:      "${1}$2 second ago${3}",
		`(\A|\W|_)hace (\d+) s(\z|\W|_)`:             "${1}$2 second ago${3}",
		`(\A|\W|_)setiembre(\z|\W|_)`:                "${1}september${2}",
		`(\A|\W|_)sep(\z|\W|_)`:                      "${1}september${2}",
		`(\A|\W|_)set(\z|\W|_)`:                      "${1}september${2}",
		`(\A|\W|_)lu(\z|\W|_)`:                       "${1}monday${2}",
		`(\A|\W|_)mi(\z|\W|_)`:                       "${1}wednesday${2}",
		`(\A|\W|_)ju(\z|\W|_)`:                       "${1}thursday${2}",
		`(\A|\W|_)vi(\z|\W|_)`:                       "${1}friday${2}",
		`(\A|\W|_)sa(\z|\W|_)`:                       "${1}saturday${2}",
		`(\A|\W|_)do(\z|\W|_)`:                       "${1}sunday${2}",
		`(\A|\W|_)años(\z|\W|_)`:                     "${1}year${2}",
		`(\A|\W|_)meses(\z|\W|_)`:                    "${1}month${2}",
		`(\A|\W|_)semanas(\z|\W|_)`:                  "${1}week${2}",
		`(\A|\W|_)días(\z|\W|_)`:                     "${1}day${2}",
		`(\A|\W|_)horas(\z|\W|_)`:                    "${1}hour${2}",
		`(\A|\W|_)minutos(\z|\W|_)`:                  "${1}minute${2}",
		`(\A|\W|_)segundos(\z|\W|_)`:                 "${1}second${2}",
		`(\A|\W|_)en(\z|\W|_)`:                       "${1}in${2}",
		`(\A|\W|_)hace(\z|\W|_)`:                     "${1}ago${2}",
		`(\A|\W|_)anteayer(\z|\W|_)`:                 "${1}2 day ago${2}",
	},
}

var es_419_Locale = LocaleData{
	Name:      "es-419",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_AR_Locale = LocaleData{
	Name:      "es-AR",
	Parent:    &es_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`(\A|\W|_)seg(\z|\W|_)`:                 "${1}second${2}",
		`(\A|\W|_)dentro de (\d+) seg(\z|\W|_)`: "${1}in $2 second${3}",
		`(\A|\W|_)hace (\d+) seg(\z|\W|_)`:      "${1}$2 second ago${3}",
	},
}

var es_BO_Locale = LocaleData{
	Name:      "es-BO",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_BR_Locale = LocaleData{
	Name:      "es-BR",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_BZ_Locale = LocaleData{
	Name:      "es-BZ",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_CL_Locale = LocaleData{
	Name:      "es-CL",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_CO_Locale = LocaleData{
	Name:      "es-CO",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_CR_Locale = LocaleData{
	Name:      "es-CR",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_CU_Locale = LocaleData{
	Name:      "es-CU",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_DO_Locale = LocaleData{
	Name:      "es-DO",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_EA_Locale = LocaleData{
	Name:      "es-EA",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_EC_Locale = LocaleData{
	Name:      "es-EC",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_GQ_Locale = LocaleData{
	Name:      "es-GQ",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_GT_Locale = LocaleData{
	Name:      "es-GT",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_HN_Locale = LocaleData{
	Name:      "es-HN",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_IC_Locale = LocaleData{
	Name:      "es-IC",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_MX_Locale = LocaleData{
	Name:      "es-MX",
	Parent:    &es_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`(\A|\W|_)el año próximo(\z|\W|_)`:    "${1}in 1 year${2}",
		`(\A|\W|_)el mes próximo(\z|\W|_)`:    "${1}in 1 month${2}",
		`(\A|\W|_)la semana próxima(\z|\W|_)`: "${1}in 1 week${2}",
		`(\A|\W|_)en (\d+) a(\z|\W|_)`:        "${1}in $2 year${3}",
		`(\A|\W|_)en (\d+) mes(\z|\W|_)`:      "${1}in $2 month${3}",
		`(\A|\W|_)en (\d+) meses(\z|\W|_)`:    "${1}in $2 month${3}",
		`(\A|\W|_)en (\d+) m(\z|\W|_)`:        "${1}in $2 month${3}",
		`(\A|\W|_)en (\d+) sem(\z|\W|_)`:      "${1}in $2 week${3}",
		`(\A|\W|_)en (\d+) día(\z|\W|_)`:      "${1}in $2 day${3}",
		`(\A|\W|_)en (\d+) días(\z|\W|_)`:     "${1}in $2 day${3}",
		`(\A|\W|_)en (\d+) h(\z|\W|_)`:        "${1}in $2 hour${3}",
		`(\A|\W|_)en (\d+) n(\z|\W|_)`:        "${1}in $2 hour${3}",
		`(\A|\W|_)en (\d+) min(\z|\W|_)`:      "${1}in $2 minute${3}",
		`(\A|\W|_)en (\d+) s(\z|\W|_)`:        "${1}in $2 second${3}",
	},
}

var es_NI_Locale = LocaleData{
	Name:      "es-NI",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_PA_Locale = LocaleData{
	Name:      "es-PA",
	Parent:    &es_Locale,
	DateOrder: "MDY",
}

var es_PE_Locale = LocaleData{
	Name:      "es-PE",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_PH_Locale = LocaleData{
	Name:      "es-PH",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_PR_Locale = LocaleData{
	Name:      "es-PR",
	Parent:    &es_Locale,
	DateOrder: "MDY",
}

var es_PY_Locale = LocaleData{
	Name:      "es-PY",
	Parent:    &es_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`(\A|\W|_)seg(\z|\W|_)`:                 "${1}second${2}",
		`(\A|\W|_)dentro de (\d+) seg(\z|\W|_)`: "${1}in $2 second${3}",
		`(\A|\W|_)hace (\d+) seg(\z|\W|_)`:      "${1}$2 second ago${3}",
	},
}

var es_SV_Locale = LocaleData{
	Name:      "es-SV",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_US_Locale = LocaleData{
	Name:      "es-US",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_UY_Locale = LocaleData{
	Name:      "es-UY",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_VE_Locale = LocaleData{
	Name:      "es-VE",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}
