// Code is generated by script; DO NOT EDIT.

package data

var es_Locale = LocaleData{
	Name:         "es",
	DateOrder:    "DMY",
	SkipWords:    []string{"'", ",", "-", ".", "/", ";", "@", "[", "]", "a las", "cerca", "de", "del", "en", "y", "|"},
	PertainWords: []string{"de", "del"},
	Simplifications: map[string]string{
		`un`:  "1",
		`una`: "1",
	},
	Translations: map[string]string{
		`enero`:                    "january",
		`ene`:                      "january",
		`febrero`:                  "february",
		`feb`:                      "february",
		`marzo`:                    "march",
		`mar`:                      "march",
		`abril`:                    "april",
		`abr`:                      "april",
		`mayo`:                     "may",
		`may`:                      "may",
		`junio`:                    "june",
		`jun`:                      "june",
		`julio`:                    "july",
		`jul`:                      "july",
		`agosto`:                   "august",
		`ago`:                      "august",
		`septiembre`:               "september",
		`sept`:                     "september",
		`octubre`:                  "october",
		`oct`:                      "october",
		`noviembre`:                "november",
		`nov`:                      "november",
		`diciembre`:                "december",
		`dic`:                      "december",
		`lunes`:                    "monday",
		`lun`:                      "monday",
		`martes`:                   "tuesday",
		`miércoles`:                "wednesday",
		`mié`:                      "wednesday",
		`jueves`:                   "thursday",
		`jue`:                      "thursday",
		`viernes`:                  "friday",
		`vie`:                      "friday",
		`sábado`:                   "saturday",
		`sáb`:                      "saturday",
		`domingo`:                  "sunday",
		`dom`:                      "sunday",
		`am`:                       "am",
		`pm`:                       "pm",
		`año`:                      "year",
		`a`:                        "year",
		`mes`:                      "month",
		`m`:                        "month",
		`semana`:                   "week",
		`sem`:                      "week",
		`día`:                      "day",
		`d`:                        "day",
		`hora`:                     "hour",
		`h`:                        "hour",
		`segundo`:                  "second",
		`s`:                        "second",
		`el año pasado`:            "1 year ago",
		`este año`:                 "0 year ago",
		`el próximo año`:           "in 1 year",
		`el mes pasado`:            "1 month ago",
		`este mes`:                 "0 month ago",
		`el próximo mes`:           "in 1 month",
		`la semana pasada`:         "1 week ago",
		`esta semana`:              "0 week ago",
		`la próxima semana`:        "in 1 week",
		`ayer`:                     "1 day ago",
		`hoy`:                      "0 day ago",
		`mañana`:                   "in 1 day",
		`esta hora`:                "0 hour ago",
		`este minuto`:              "0 minute ago",
		`ahora`:                    "0 second ago",
		`dentro de (\d+) año`:      "in $1 year",
		`dentro de (\d+) años`:     "in $1 year",
		`dentro de (\d+) a`:        "in $1 year",
		`hace (\d+) año`:           "$1 year ago",
		`hace (\d+) años`:          "$1 year ago",
		`hace (\d+) a`:             "$1 year ago",
		`dentro de (\d+) mes`:      "in $1 month",
		`dentro de (\d+) meses`:    "in $1 month",
		`dentro de (\d+) m`:        "in $1 month",
		`hace (\d+) mes`:           "$1 month ago",
		`hace (\d+) meses`:         "$1 month ago",
		`hace (\d+) m`:             "$1 month ago",
		`dentro de (\d+) semana`:   "in $1 week",
		`dentro de (\d+) semanas`:  "in $1 week",
		`dentro de (\d+) sem`:      "in $1 week",
		`hace (\d+) semana`:        "$1 week ago",
		`hace (\d+) semanas`:       "$1 week ago",
		`hace (\d+) sem`:           "$1 week ago",
		`dentro de (\d+) día`:      "in $1 day",
		`dentro de (\d+) días`:     "in $1 day",
		`hace (\d+) día`:           "$1 day ago",
		`hace (\d+) días`:          "$1 day ago",
		`dentro de (\d+) hora`:     "in $1 hour",
		`dentro de (\d+) horas`:    "in $1 hour",
		`dentro de (\d+) h`:        "in $1 hour",
		`hace (\d+) hora`:          "$1 hour ago",
		`hace (\d+) horas`:         "$1 hour ago",
		`hace (\d+) h`:             "$1 hour ago",
		`dentro de (\d+) minuto`:   "in $1 minute",
		`dentro de (\d+) minutos`:  "in $1 minute",
		`dentro de (\d+) min`:      "in $1 minute",
		`dentro de (\d+) segundo`:  "in $1 second",
		`dentro de (\d+) segundos`: "in $1 second",
		`dentro de (\d+) s`:        "in $1 second",
		`hace (\d+) segundo`:       "$1 second ago",
		`hace (\d+) segundos`:      "$1 second ago",
		`hace (\d+) s`:             "$1 second ago",
		`setiembre`:                "september",
		`sep`:                      "september",
		`set`:                      "september",
		`lu`:                       "monday",
		`mi`:                       "wednesday",
		`ju`:                       "thursday",
		`vi`:                       "friday",
		`sa`:                       "saturday",
		`do`:                       "sunday",
		`años`:                     "year",
		`meses`:                    "month",
		`semanas`:                  "week",
		`días`:                     "day",
		`horas`:                    "hour",
		`minutos`:                  "minute",
		`segundos`:                 "second",
		`en`:                       "in",
		`hace`:                     "ago",
		`anteayer`:                 "2 day ago",
	},
}

var es_419_Locale = LocaleData{
	Name:      "es-419",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_AR_Locale = LocaleData{
	Name:      "es-AR",
	Parent:    &es_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`seg`:                 "second",
		`dentro de (\d+) seg`: "in $1 second",
		`hace (\d+) seg`:      "$1 second ago",
	},
}

var es_BO_Locale = LocaleData{
	Name:      "es-BO",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_BR_Locale = LocaleData{
	Name:      "es-BR",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_BZ_Locale = LocaleData{
	Name:      "es-BZ",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_CL_Locale = LocaleData{
	Name:      "es-CL",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_CO_Locale = LocaleData{
	Name:      "es-CO",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_CR_Locale = LocaleData{
	Name:      "es-CR",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_CU_Locale = LocaleData{
	Name:      "es-CU",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_DO_Locale = LocaleData{
	Name:      "es-DO",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_EA_Locale = LocaleData{
	Name:      "es-EA",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_EC_Locale = LocaleData{
	Name:      "es-EC",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_GQ_Locale = LocaleData{
	Name:      "es-GQ",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_GT_Locale = LocaleData{
	Name:      "es-GT",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_HN_Locale = LocaleData{
	Name:      "es-HN",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_IC_Locale = LocaleData{
	Name:      "es-IC",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_MX_Locale = LocaleData{
	Name:      "es-MX",
	Parent:    &es_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`el año próximo`:    "in 1 year",
		`el mes próximo`:    "in 1 month",
		`la semana próxima`: "in 1 week",
		`en (\d+) a`:        "in $1 year",
		`en (\d+) mes`:      "in $1 month",
		`en (\d+) meses`:    "in $1 month",
		`en (\d+) m`:        "in $1 month",
		`en (\d+) sem`:      "in $1 week",
		`en (\d+) día`:      "in $1 day",
		`en (\d+) días`:     "in $1 day",
		`en (\d+) h`:        "in $1 hour",
		`en (\d+) n`:        "in $1 hour",
		`en (\d+) min`:      "in $1 minute",
		`en (\d+) s`:        "in $1 second",
	},
}

var es_NI_Locale = LocaleData{
	Name:      "es-NI",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_PA_Locale = LocaleData{
	Name:      "es-PA",
	Parent:    &es_Locale,
	DateOrder: "MDY",
}

var es_PE_Locale = LocaleData{
	Name:      "es-PE",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_PH_Locale = LocaleData{
	Name:      "es-PH",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_PR_Locale = LocaleData{
	Name:      "es-PR",
	Parent:    &es_Locale,
	DateOrder: "MDY",
}

var es_PY_Locale = LocaleData{
	Name:      "es-PY",
	Parent:    &es_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`seg`:                 "second",
		`dentro de (\d+) seg`: "in $1 second",
		`hace (\d+) seg`:      "$1 second ago",
	},
}

var es_SV_Locale = LocaleData{
	Name:      "es-SV",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_US_Locale = LocaleData{
	Name:      "es-US",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_UY_Locale = LocaleData{
	Name:      "es-UY",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}

var es_VE_Locale = LocaleData{
	Name:      "es-VE",
	Parent:    &es_Locale,
	DateOrder: "DMY",
}
