// Code is generated by script; DO NOT EDIT.

package data

import "github.com/markusmobius/go-dateparser/internal/regexp"

var (
	es_Locale     LocaleData
	es_419_Locale LocaleData
	es_AR_Locale  LocaleData
	es_BO_Locale  LocaleData
	es_BR_Locale  LocaleData
	es_BZ_Locale  LocaleData
	es_CL_Locale  LocaleData
	es_CO_Locale  LocaleData
	es_CR_Locale  LocaleData
	es_CU_Locale  LocaleData
	es_DO_Locale  LocaleData
	es_EA_Locale  LocaleData
	es_EC_Locale  LocaleData
	es_GQ_Locale  LocaleData
	es_GT_Locale  LocaleData
	es_HN_Locale  LocaleData
	es_IC_Locale  LocaleData
	es_MX_Locale  LocaleData
	es_NI_Locale  LocaleData
	es_PA_Locale  LocaleData
	es_PE_Locale  LocaleData
	es_PH_Locale  LocaleData
	es_PR_Locale  LocaleData
	es_PY_Locale  LocaleData
	es_SV_Locale  LocaleData
	es_US_Locale  LocaleData
	es_UY_Locale  LocaleData
	es_VE_Locale  LocaleData
)

func init() {
	es_Locale = merge(nil, LocaleData{
		Name:                  "es",
		DateOrder:             "DMY",
		Charset:               []rune(`bcdefghijlnorstuvxyzáéíñó`),
		SentenceSplitterGroup: 2,
		Simplifications: []ReplacementData{
			{regexp.MustCompile(`(?i)(\A|[^\pL\pM\d_])una(\z|[^\pL\pM\d_])`), "${1}1${2}"},
			{regexp.MustCompile(`(?i)(\A|[^\pL\pM\d_])un(\z|[^\pL\pM\d_])`), "${1}1${2}"},
		},
		Translations: map[string][]string{
			"septiembre": {"september"},
			"diciembre":  {"december"},
			"miercoles":  {"wednesday"},
			"noviembre":  {"november"},
			"setiembre":  {"september"},
			"segundos":   {"second"},
			"domingo":    {"sunday"},
			"febrero":    {"february"},
			"minutos":    {"minute"},
			"octubre":    {"october"},
			"segundo":    {"second"},
			"semanas":    {"week"},
			"viernes":    {"friday"},
			"agosto":     {"august"},
			"jueves":     {"thursday"},
			"martes":     {"tuesday"},
			"minuto":     {"minute"},
			"sabado":     {"saturday"},
			"semana":     {"week"},
			"a las":      {""},
			"abril":      {"april"},
			"cerca":      {""},
			"enero":      {"january"},
			"horas":      {"hour"},
			"julio":      {"july"},
			"junio":      {"june"},
			"lunes":      {"monday"},
			"marzo":      {"march"},
			"meses":      {"month"},
			"anos":       {"year"},
			"dias":       {"day"},
			"hace":       {"ago"},
			"hora":       {"hour"},
			"mayo":       {"may"},
			"sept":       {"september"},
			"abr":        {"april"},
			"ago":        {"august"},
			"ano":        {"year"},
			"del":        {""},
			"dia":        {"day"},
			"dic":        {"december"},
			"dom":        {"sunday"},
			"ene":        {"january"},
			"feb":        {"february"},
			"gmt":        {"gmt"},
			"jue":        {"thursday"},
			"jul":        {"july"},
			"jun":        {"june"},
			"lun":        {"monday"},
			"mar":        {"march", "tuesday"},
			"may":        {"may"},
			"mes":        {"month"},
			"mie":        {"wednesday"},
			"min":        {"minute"},
			"nov":        {"november"},
			"oct":        {"october"},
			"sab":        {"saturday"},
			"sem":        {"week"},
			"sep":        {"september"},
			"set":        {"september"},
			"utc":        {"utc"},
			"vie":        {"friday"},
			"am":         {"am"},
			"de":         {""},
			"do":         {"sunday"},
			"en":         {"in"},
			"ju":         {"thursday"},
			"lu":         {"monday"},
			"mi":         {"wednesday"},
			"pm":         {"pm"},
			"sa":         {"saturday"},
			"vi":         {"friday"},
			" ":          {" "},
			"'":          {""},
			"+":          {"+"},
			",":          {""},
			"-":          {"-"},
			".":          {"."},
			"/":          {"/"},
			":":          {":"},
			";":          {""},
			"@":          {""},
			"[":          {""},
			"]":          {""},
			"a":          {"year"},
			"d":          {"day"},
			"h":          {"hour"},
			"m":          {"month"},
			"s":          {"second"},
			"y":          {""},
			"z":          {"z"},
			"|":          {""},
		},
		RelativeType: map[string]string{
			"la proxima semana": "in 1 week",
			"la semana pasada":  "1 week ago",
			"el proximo ano":    "in 1 year",
			"el proximo mes":    "in 1 month",
			"el ano pasado":     "1 year ago",
			"el mes pasado":     "1 month ago",
			"esta semana":       "0 week ago",
			"este minuto":       "0 minute ago",
			"esta hora":         "0 hour ago",
			"anteayer":          "2 day ago",
			"este ano":          "0 year ago",
			"este mes":          "0 month ago",
			"manana":            "in 1 day",
			"ahora":             "0 second ago",
			"ayer":              "1 day ago",
			"hoy":               "0 day ago",
		},
		RelativeTypeRegexes: []ReplacementData{
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) segundos`), "in $1 second"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) minutos`), "in $1 minute"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) segundo`), "in $1 second"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) semanas`), "in $1 week"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) minuto`), "in $1 minute"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) semana`), "in $1 week"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) horas`), "in $1 hour"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) meses`), "in $1 month"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) anos`), "in $1 year"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) dias`), "in $1 day"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) hora`), "in $1 hour"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) ano`), "in $1 year"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) dia`), "in $1 day"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) mes`), "in $1 month"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) min`), "in $1 minute"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) sem`), "in $1 week"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) segundos`), "$1 second ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) minutos`), "$1 minute ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) segundo`), "$1 second ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) semanas`), "$1 week ago"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) a`), "in $1 year"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) h`), "in $1 hour"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) m`), "in $1 month"},
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) s`), "in $1 second"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) minuto`), "$1 minute ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) semana`), "$1 week ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) horas`), "$1 hour ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) meses`), "$1 month ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) anos`), "$1 year ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) dias`), "$1 day ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) hora`), "$1 hour ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) ano`), "$1 year ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) dia`), "$1 day ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) mes`), "$1 month ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) min`), "$1 minute ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) sem`), "$1 week ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) a`), "$1 year ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) h`), "$1 hour ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) m`), "$1 month ago"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) s`), "$1 second ago"},
		},
		RxCombined:      regexp.MustCompile(`(?i)(\A|[^\pL\pM\d]|_)(dentro de \d+[.,]?\d* segundos|dentro de \d+[.,]?\d* minutos|dentro de \d+[.,]?\d* segundo|dentro de \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* minuto|dentro de \d+[.,]?\d* semana|dentro de \d+[.,]?\d* horas|dentro de \d+[.,]?\d* meses|dentro de \d+[.,]?\d* anos|dentro de \d+[.,]?\d* dias|dentro de \d+[.,]?\d* hora|dentro de \d+[.,]?\d* ano|dentro de \d+[.,]?\d* dia|dentro de \d+[.,]?\d* mes|dentro de \d+[.,]?\d* min|dentro de \d+[.,]?\d* sem|hace \d+[.,]?\d* segundos|hace \d+[.,]?\d* minutos|hace \d+[.,]?\d* segundo|hace \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* a|dentro de \d+[.,]?\d* h|dentro de \d+[.,]?\d* m|dentro de \d+[.,]?\d* s|hace \d+[.,]?\d* minuto|hace \d+[.,]?\d* semana|hace \d+[.,]?\d* horas|hace \d+[.,]?\d* meses|hace \d+[.,]?\d* anos|hace \d+[.,]?\d* dias|hace \d+[.,]?\d* hora|hace \d+[.,]?\d* ano|hace \d+[.,]?\d* dia|hace \d+[.,]?\d* mes|hace \d+[.,]?\d* min|hace \d+[.,]?\d* sem|hace \d+[.,]?\d* a|hace \d+[.,]?\d* h|hace \d+[.,]?\d* m|hace \d+[.,]?\d* s)(\z|[^\pL\pM\d]|_)`),
		RxExactCombined: regexp.MustCompile(`(?i)^(dentro de \d+[.,]?\d* segundos|dentro de \d+[.,]?\d* minutos|dentro de \d+[.,]?\d* segundo|dentro de \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* minuto|dentro de \d+[.,]?\d* semana|dentro de \d+[.,]?\d* horas|dentro de \d+[.,]?\d* meses|dentro de \d+[.,]?\d* anos|dentro de \d+[.,]?\d* dias|dentro de \d+[.,]?\d* hora|dentro de \d+[.,]?\d* ano|dentro de \d+[.,]?\d* dia|dentro de \d+[.,]?\d* mes|dentro de \d+[.,]?\d* min|dentro de \d+[.,]?\d* sem|hace \d+[.,]?\d* segundos|hace \d+[.,]?\d* minutos|hace \d+[.,]?\d* segundo|hace \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* a|dentro de \d+[.,]?\d* h|dentro de \d+[.,]?\d* m|dentro de \d+[.,]?\d* s|hace \d+[.,]?\d* minuto|hace \d+[.,]?\d* semana|hace \d+[.,]?\d* horas|hace \d+[.,]?\d* meses|hace \d+[.,]?\d* anos|hace \d+[.,]?\d* dias|hace \d+[.,]?\d* hora|hace \d+[.,]?\d* ano|hace \d+[.,]?\d* dia|hace \d+[.,]?\d* mes|hace \d+[.,]?\d* min|hace \d+[.,]?\d* sem|hace \d+[.,]?\d* a|hace \d+[.,]?\d* h|hace \d+[.,]?\d* m|hace \d+[.,]?\d* s)$`),
		KnownWords:      []string{"la proxima semana", "la semana pasada", "el proximo ano", "el proximo mes", "el ano pasado", "el mes pasado", "esta semana", "este minuto", "septiembre", "diciembre", "esta hora", "miercoles", "noviembre", "setiembre", "anteayer", "este ano", "este mes", "segundos", "domingo", "febrero", "minutos", "octubre", "segundo", "semanas", "viernes", "agosto", "jueves", "manana", "martes", "minuto", "sabado", "semana", "a las", "abril", "ahora", "cerca", "enero", "horas", "julio", "junio", "lunes", "marzo", "meses", "anos", "ayer", "dias", "hace", "hora", "mayo", "sept", "abr", "ago", "ano", "del", "dia", "dic", "dom", "ene", "feb", "gmt", "hoy", "jue", "jul", "jun", "lun", "mar", "may", "mes", "mie", "min", "nov", "oct", "sab", "sem", "sep", "set", "utc", "vie", "am", "de", "do", "en", "ju", "lu", "mi", "pm", "sa", "vi", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "a", "d", "h", "m", "s", "y", "z", "|"},
	})

	es_419_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-419",
		DateOrder: "DMY",
	})

	es_AR_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-AR",
		DateOrder: "DMY",
		Translations: map[string][]string{
			"seg": {"second"},
		},
		RelativeTypeRegexes: []ReplacementData{
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) seg`), "in $1 second"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) seg`), "$1 second ago"},
		},
		RxCombined:      regexp.MustCompile(`(?i)(\A|[^\pL\pM\d]|_)(dentro de \d+[.,]?\d* segundos|dentro de \d+[.,]?\d* minutos|dentro de \d+[.,]?\d* segundo|dentro de \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* minuto|dentro de \d+[.,]?\d* semana|dentro de \d+[.,]?\d* horas|dentro de \d+[.,]?\d* meses|dentro de \d+[.,]?\d* anos|dentro de \d+[.,]?\d* dias|dentro de \d+[.,]?\d* hora|dentro de \d+[.,]?\d* ano|dentro de \d+[.,]?\d* dia|dentro de \d+[.,]?\d* mes|dentro de \d+[.,]?\d* min|dentro de \d+[.,]?\d* seg|dentro de \d+[.,]?\d* sem|hace \d+[.,]?\d* segundos|hace \d+[.,]?\d* minutos|hace \d+[.,]?\d* segundo|hace \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* a|dentro de \d+[.,]?\d* h|dentro de \d+[.,]?\d* m|dentro de \d+[.,]?\d* s|hace \d+[.,]?\d* minuto|hace \d+[.,]?\d* semana|hace \d+[.,]?\d* horas|hace \d+[.,]?\d* meses|hace \d+[.,]?\d* anos|hace \d+[.,]?\d* dias|hace \d+[.,]?\d* hora|hace \d+[.,]?\d* ano|hace \d+[.,]?\d* dia|hace \d+[.,]?\d* mes|hace \d+[.,]?\d* min|hace \d+[.,]?\d* seg|hace \d+[.,]?\d* sem|hace \d+[.,]?\d* a|hace \d+[.,]?\d* h|hace \d+[.,]?\d* m|hace \d+[.,]?\d* s)(\z|[^\pL\pM\d]|_)`),
		RxExactCombined: regexp.MustCompile(`(?i)^(dentro de \d+[.,]?\d* segundos|dentro de \d+[.,]?\d* minutos|dentro de \d+[.,]?\d* segundo|dentro de \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* minuto|dentro de \d+[.,]?\d* semana|dentro de \d+[.,]?\d* horas|dentro de \d+[.,]?\d* meses|dentro de \d+[.,]?\d* anos|dentro de \d+[.,]?\d* dias|dentro de \d+[.,]?\d* hora|dentro de \d+[.,]?\d* ano|dentro de \d+[.,]?\d* dia|dentro de \d+[.,]?\d* mes|dentro de \d+[.,]?\d* min|dentro de \d+[.,]?\d* seg|dentro de \d+[.,]?\d* sem|hace \d+[.,]?\d* segundos|hace \d+[.,]?\d* minutos|hace \d+[.,]?\d* segundo|hace \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* a|dentro de \d+[.,]?\d* h|dentro de \d+[.,]?\d* m|dentro de \d+[.,]?\d* s|hace \d+[.,]?\d* minuto|hace \d+[.,]?\d* semana|hace \d+[.,]?\d* horas|hace \d+[.,]?\d* meses|hace \d+[.,]?\d* anos|hace \d+[.,]?\d* dias|hace \d+[.,]?\d* hora|hace \d+[.,]?\d* ano|hace \d+[.,]?\d* dia|hace \d+[.,]?\d* mes|hace \d+[.,]?\d* min|hace \d+[.,]?\d* seg|hace \d+[.,]?\d* sem|hace \d+[.,]?\d* a|hace \d+[.,]?\d* h|hace \d+[.,]?\d* m|hace \d+[.,]?\d* s)$`),
		KnownWords:      []string{"la proxima semana", "la semana pasada", "el proximo ano", "el proximo mes", "el ano pasado", "el mes pasado", "esta semana", "este minuto", "septiembre", "diciembre", "esta hora", "miercoles", "noviembre", "setiembre", "anteayer", "este ano", "este mes", "segundos", "domingo", "febrero", "minutos", "octubre", "segundo", "semanas", "viernes", "agosto", "jueves", "manana", "martes", "minuto", "sabado", "semana", "a las", "abril", "ahora", "cerca", "enero", "horas", "julio", "junio", "lunes", "marzo", "meses", "anos", "ayer", "dias", "hace", "hora", "mayo", "sept", "abr", "ago", "ano", "del", "dia", "dic", "dom", "ene", "feb", "gmt", "hoy", "jue", "jul", "jun", "lun", "mar", "may", "mes", "mie", "min", "nov", "oct", "sab", "seg", "sem", "sep", "set", "utc", "vie", "am", "de", "do", "en", "ju", "lu", "mi", "pm", "sa", "vi", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "a", "d", "h", "m", "s", "y", "z", "|"},
	})

	es_BO_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-BO",
		DateOrder: "DMY",
	})

	es_BR_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-BR",
		DateOrder: "DMY",
	})

	es_BZ_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-BZ",
		DateOrder: "DMY",
	})

	es_CL_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-CL",
		DateOrder: "DMY",
	})

	es_CO_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-CO",
		DateOrder: "DMY",
	})

	es_CR_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-CR",
		DateOrder: "DMY",
	})

	es_CU_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-CU",
		DateOrder: "DMY",
	})

	es_DO_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-DO",
		DateOrder: "DMY",
	})

	es_EA_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-EA",
		DateOrder: "DMY",
	})

	es_EC_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-EC",
		DateOrder: "DMY",
	})

	es_GQ_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-GQ",
		DateOrder: "DMY",
	})

	es_GT_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-GT",
		DateOrder: "DMY",
	})

	es_HN_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-HN",
		DateOrder: "DMY",
	})

	es_IC_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-IC",
		DateOrder: "DMY",
	})

	es_MX_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-MX",
		DateOrder: "DMY",
		RelativeType: map[string]string{
			"la semana proxima": "in 1 week",
			"el ano proximo":    "in 1 year",
			"el mes proximo":    "in 1 month",
		},
		RelativeTypeRegexes: []ReplacementData{
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) meses`), "in $1 month"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) dias`), "in $1 day"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) dia`), "in $1 day"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) mes`), "in $1 month"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) min`), "in $1 minute"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) sem`), "in $1 week"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) a`), "in $1 year"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) h`), "in $1 hour"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) m`), "in $1 month"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) n`), "in $1 hour"},
			{regexp.MustCompile(`(?i)en (\d+[.,]?\d*) s`), "in $1 second"},
		},
		RxCombined:      regexp.MustCompile(`(?i)(\A|[^\pL\pM\d]|_)(dentro de \d+[.,]?\d* segundos|dentro de \d+[.,]?\d* minutos|dentro de \d+[.,]?\d* segundo|dentro de \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* minuto|dentro de \d+[.,]?\d* semana|dentro de \d+[.,]?\d* horas|dentro de \d+[.,]?\d* meses|dentro de \d+[.,]?\d* anos|dentro de \d+[.,]?\d* dias|dentro de \d+[.,]?\d* hora|dentro de \d+[.,]?\d* ano|dentro de \d+[.,]?\d* dia|dentro de \d+[.,]?\d* mes|dentro de \d+[.,]?\d* min|dentro de \d+[.,]?\d* sem|hace \d+[.,]?\d* segundos|hace \d+[.,]?\d* minutos|hace \d+[.,]?\d* segundo|hace \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* a|dentro de \d+[.,]?\d* h|dentro de \d+[.,]?\d* m|dentro de \d+[.,]?\d* s|hace \d+[.,]?\d* minuto|hace \d+[.,]?\d* semana|hace \d+[.,]?\d* horas|hace \d+[.,]?\d* meses|hace \d+[.,]?\d* anos|hace \d+[.,]?\d* dias|hace \d+[.,]?\d* hora|en \d+[.,]?\d* meses|hace \d+[.,]?\d* ano|hace \d+[.,]?\d* dia|hace \d+[.,]?\d* mes|hace \d+[.,]?\d* min|hace \d+[.,]?\d* sem|en \d+[.,]?\d* dias|en \d+[.,]?\d* dia|en \d+[.,]?\d* mes|en \d+[.,]?\d* min|en \d+[.,]?\d* sem|hace \d+[.,]?\d* a|hace \d+[.,]?\d* h|hace \d+[.,]?\d* m|hace \d+[.,]?\d* s|en \d+[.,]?\d* a|en \d+[.,]?\d* h|en \d+[.,]?\d* m|en \d+[.,]?\d* n|en \d+[.,]?\d* s)(\z|[^\pL\pM\d]|_)`),
		RxExactCombined: regexp.MustCompile(`(?i)^(dentro de \d+[.,]?\d* segundos|dentro de \d+[.,]?\d* minutos|dentro de \d+[.,]?\d* segundo|dentro de \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* minuto|dentro de \d+[.,]?\d* semana|dentro de \d+[.,]?\d* horas|dentro de \d+[.,]?\d* meses|dentro de \d+[.,]?\d* anos|dentro de \d+[.,]?\d* dias|dentro de \d+[.,]?\d* hora|dentro de \d+[.,]?\d* ano|dentro de \d+[.,]?\d* dia|dentro de \d+[.,]?\d* mes|dentro de \d+[.,]?\d* min|dentro de \d+[.,]?\d* sem|hace \d+[.,]?\d* segundos|hace \d+[.,]?\d* minutos|hace \d+[.,]?\d* segundo|hace \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* a|dentro de \d+[.,]?\d* h|dentro de \d+[.,]?\d* m|dentro de \d+[.,]?\d* s|hace \d+[.,]?\d* minuto|hace \d+[.,]?\d* semana|hace \d+[.,]?\d* horas|hace \d+[.,]?\d* meses|hace \d+[.,]?\d* anos|hace \d+[.,]?\d* dias|hace \d+[.,]?\d* hora|en \d+[.,]?\d* meses|hace \d+[.,]?\d* ano|hace \d+[.,]?\d* dia|hace \d+[.,]?\d* mes|hace \d+[.,]?\d* min|hace \d+[.,]?\d* sem|en \d+[.,]?\d* dias|en \d+[.,]?\d* dia|en \d+[.,]?\d* mes|en \d+[.,]?\d* min|en \d+[.,]?\d* sem|hace \d+[.,]?\d* a|hace \d+[.,]?\d* h|hace \d+[.,]?\d* m|hace \d+[.,]?\d* s|en \d+[.,]?\d* a|en \d+[.,]?\d* h|en \d+[.,]?\d* m|en \d+[.,]?\d* n|en \d+[.,]?\d* s)$`),
		KnownWords:      []string{"la proxima semana", "la semana proxima", "la semana pasada", "el ano proximo", "el mes proximo", "el proximo ano", "el proximo mes", "el ano pasado", "el mes pasado", "esta semana", "este minuto", "septiembre", "diciembre", "esta hora", "miercoles", "noviembre", "setiembre", "anteayer", "este ano", "este mes", "segundos", "domingo", "febrero", "minutos", "octubre", "segundo", "semanas", "viernes", "agosto", "jueves", "manana", "martes", "minuto", "sabado", "semana", "a las", "abril", "ahora", "cerca", "enero", "horas", "julio", "junio", "lunes", "marzo", "meses", "anos", "ayer", "dias", "hace", "hora", "mayo", "sept", "abr", "ago", "ano", "del", "dia", "dic", "dom", "ene", "feb", "gmt", "hoy", "jue", "jul", "jun", "lun", "mar", "may", "mes", "mie", "min", "nov", "oct", "sab", "sem", "sep", "set", "utc", "vie", "am", "de", "do", "en", "ju", "lu", "mi", "pm", "sa", "vi", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "a", "d", "h", "m", "s", "y", "z", "|"},
	})

	es_NI_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-NI",
		DateOrder: "DMY",
	})

	es_PA_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-PA",
		DateOrder: "MDY",
	})

	es_PE_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-PE",
		DateOrder: "DMY",
	})

	es_PH_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-PH",
		DateOrder: "DMY",
	})

	es_PR_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-PR",
		DateOrder: "MDY",
	})

	es_PY_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-PY",
		DateOrder: "DMY",
		Translations: map[string][]string{
			"seg": {"second"},
		},
		RelativeTypeRegexes: []ReplacementData{
			{regexp.MustCompile(`(?i)dentro de (\d+[.,]?\d*) seg`), "in $1 second"},
			{regexp.MustCompile(`(?i)hace (\d+[.,]?\d*) seg`), "$1 second ago"},
		},
		RxCombined:      regexp.MustCompile(`(?i)(\A|[^\pL\pM\d]|_)(dentro de \d+[.,]?\d* segundos|dentro de \d+[.,]?\d* minutos|dentro de \d+[.,]?\d* segundo|dentro de \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* minuto|dentro de \d+[.,]?\d* semana|dentro de \d+[.,]?\d* horas|dentro de \d+[.,]?\d* meses|dentro de \d+[.,]?\d* anos|dentro de \d+[.,]?\d* dias|dentro de \d+[.,]?\d* hora|dentro de \d+[.,]?\d* ano|dentro de \d+[.,]?\d* dia|dentro de \d+[.,]?\d* mes|dentro de \d+[.,]?\d* min|dentro de \d+[.,]?\d* seg|dentro de \d+[.,]?\d* sem|hace \d+[.,]?\d* segundos|hace \d+[.,]?\d* minutos|hace \d+[.,]?\d* segundo|hace \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* a|dentro de \d+[.,]?\d* h|dentro de \d+[.,]?\d* m|dentro de \d+[.,]?\d* s|hace \d+[.,]?\d* minuto|hace \d+[.,]?\d* semana|hace \d+[.,]?\d* horas|hace \d+[.,]?\d* meses|hace \d+[.,]?\d* anos|hace \d+[.,]?\d* dias|hace \d+[.,]?\d* hora|hace \d+[.,]?\d* ano|hace \d+[.,]?\d* dia|hace \d+[.,]?\d* mes|hace \d+[.,]?\d* min|hace \d+[.,]?\d* seg|hace \d+[.,]?\d* sem|hace \d+[.,]?\d* a|hace \d+[.,]?\d* h|hace \d+[.,]?\d* m|hace \d+[.,]?\d* s)(\z|[^\pL\pM\d]|_)`),
		RxExactCombined: regexp.MustCompile(`(?i)^(dentro de \d+[.,]?\d* segundos|dentro de \d+[.,]?\d* minutos|dentro de \d+[.,]?\d* segundo|dentro de \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* minuto|dentro de \d+[.,]?\d* semana|dentro de \d+[.,]?\d* horas|dentro de \d+[.,]?\d* meses|dentro de \d+[.,]?\d* anos|dentro de \d+[.,]?\d* dias|dentro de \d+[.,]?\d* hora|dentro de \d+[.,]?\d* ano|dentro de \d+[.,]?\d* dia|dentro de \d+[.,]?\d* mes|dentro de \d+[.,]?\d* min|dentro de \d+[.,]?\d* seg|dentro de \d+[.,]?\d* sem|hace \d+[.,]?\d* segundos|hace \d+[.,]?\d* minutos|hace \d+[.,]?\d* segundo|hace \d+[.,]?\d* semanas|dentro de \d+[.,]?\d* a|dentro de \d+[.,]?\d* h|dentro de \d+[.,]?\d* m|dentro de \d+[.,]?\d* s|hace \d+[.,]?\d* minuto|hace \d+[.,]?\d* semana|hace \d+[.,]?\d* horas|hace \d+[.,]?\d* meses|hace \d+[.,]?\d* anos|hace \d+[.,]?\d* dias|hace \d+[.,]?\d* hora|hace \d+[.,]?\d* ano|hace \d+[.,]?\d* dia|hace \d+[.,]?\d* mes|hace \d+[.,]?\d* min|hace \d+[.,]?\d* seg|hace \d+[.,]?\d* sem|hace \d+[.,]?\d* a|hace \d+[.,]?\d* h|hace \d+[.,]?\d* m|hace \d+[.,]?\d* s)$`),
		KnownWords:      []string{"la proxima semana", "la semana pasada", "el proximo ano", "el proximo mes", "el ano pasado", "el mes pasado", "esta semana", "este minuto", "septiembre", "diciembre", "esta hora", "miercoles", "noviembre", "setiembre", "anteayer", "este ano", "este mes", "segundos", "domingo", "febrero", "minutos", "octubre", "segundo", "semanas", "viernes", "agosto", "jueves", "manana", "martes", "minuto", "sabado", "semana", "a las", "abril", "ahora", "cerca", "enero", "horas", "julio", "junio", "lunes", "marzo", "meses", "anos", "ayer", "dias", "hace", "hora", "mayo", "sept", "abr", "ago", "ano", "del", "dia", "dic", "dom", "ene", "feb", "gmt", "hoy", "jue", "jul", "jun", "lun", "mar", "may", "mes", "mie", "min", "nov", "oct", "sab", "seg", "sem", "sep", "set", "utc", "vie", "am", "de", "do", "en", "ju", "lu", "mi", "pm", "sa", "vi", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "a", "d", "h", "m", "s", "y", "z", "|"},
	})

	es_SV_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-SV",
		DateOrder: "DMY",
	})

	es_US_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-US",
		DateOrder: "DMY",
	})

	es_UY_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-UY",
		DateOrder: "DMY",
	})

	es_VE_Locale = merge(&es_Locale, LocaleData{
		Name:      "es-VE",
		DateOrder: "DMY",
	})
}
