// Code is generated by script; DO NOT EDIT.

package data

var (
	ff_Locale    LocaleData
	ff_CM_Locale LocaleData
	ff_GN_Locale LocaleData
	ff_MR_Locale LocaleData
)

func init() {
	ff_Locale = merge(nil, LocaleData{
		Name:      "ff",
		DateOrder: "DMY",
		Charset:   []rune(`-bcdeghijklnorstuwxyzñŋƴɓɗ`),
		Translations: map[string][]string{
			"hoore-biir": {"saturday"},
			"naasaande":  {"thursday"},
			"njeslaare":  {"wednesday"},
			"hitaande":   {"year"},
			"majaango":   {"second"},
			"mawbaare":   {"tuesday"},
			"yarkomaa":   {"october"},
			"kikiiɗe":    {"pm"},
			"yontere":    {"week"},
			"aaɓnde":     {"monday"},
			"duujal":     {"may"},
			"mawnde":     {"friday"},
			"nalnde":     {"day"},
			"seeɗto":     {"april"},
			"siilto":     {"september"},
			"subaka":     {"am"},
			"bowte":      {"december"},
			"colte":      {"february"},
			"hoƴom":      {"minute"},
			"jolal":      {"november"},
			"korse":      {"june"},
			"lewru":      {"month"},
			"mbooy":      {"march"},
			"morso":      {"july"},
			"siilo":      {"january"},
			"waktu":      {"hour"},
			"dewo":       {"sunday"},
			"juko":       {"august"},
			"aaɓ":        {"monday"},
			"bow":        {"december"},
			"col":        {"february"},
			"dew":        {"sunday"},
			"duu":        {"may"},
			"gmt":        {"gmt"},
			"hbi":        {"saturday"},
			"jol":        {"november"},
			"juk":        {"august"},
			"kor":        {"june"},
			"maw":        {"tuesday"},
			"mbo":        {"march"},
			"mor":        {"july"},
			"mwd":        {"friday"},
			"naa":        {"thursday"},
			"nje":        {"wednesday"},
			"see":        {"april"},
			"sii":        {"january"},
			"slt":        {"september"},
			"utc":        {"utc"},
			"yar":        {"october"},
			"am":         {"am"},
			"pm":         {"pm"},
			" ":          {" "},
			"'":          {""},
			"+":          {"+"},
			",":          {""},
			"-":          {"-"},
			".":          {"."},
			"/":          {"/"},
			":":          {":"},
			";":          {""},
			"@":          {""},
			"[":          {""},
			"]":          {""},
			"z":          {"z"},
			"|":          {""},
		},
		RelativeType: map[string]string{
			"this minute": "0 minute ago",
			"last month":  "1 month ago",
			"next month":  "in 1 month",
			"this month":  "0 month ago",
			"last week":   "1 week ago",
			"last year":   "1 year ago",
			"next week":   "in 1 week",
			"next year":   "in 1 year",
			"this hour":   "0 hour ago",
			"this week":   "0 week ago",
			"this year":   "0 year ago",
			"hannde":      "0 day ago",
			"jaŋngo":      "in 1 day",
			"haŋki":       "1 day ago",
			"now":         "0 second ago",
		},
		KnownWords: []string{"this minute", "hoore-biir", "last month", "next month", "this month", "last week", "last year", "naasaande", "next week", "next year", "njeslaare", "this hour", "this week", "this year", "hitaande", "majaango", "mawbaare", "yarkomaa", "kikiiɗe", "yontere", "aaɓnde", "duujal", "hannde", "jaŋngo", "mawnde", "nalnde", "seeɗto", "siilto", "subaka", "bowte", "colte", "haŋki", "hoƴom", "jolal", "korse", "lewru", "mbooy", "morso", "siilo", "waktu", "dewo", "juko", "aaɓ", "bow", "col", "dew", "duu", "gmt", "hbi", "jol", "juk", "kor", "maw", "mbo", "mor", "mwd", "naa", "nje", "now", "see", "sii", "slt", "utc", "yar", "am", "pm", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "z", "|"},
	})

	ff_CM_Locale = merge(&ff_Locale, LocaleData{
		Name:      "ff-CM",
		DateOrder: "DMY",
	})

	ff_GN_Locale = merge(&ff_Locale, LocaleData{
		Name:      "ff-GN",
		DateOrder: "DMY",
	})

	ff_MR_Locale = merge(&ff_Locale, LocaleData{
		Name:      "ff-MR",
		DateOrder: "DMY",
	})
}
