// Code is generated by script; DO NOT EDIT.

package data

var fr_Locale = LocaleData{
	Name:      "fr",
	DateOrder: "DMY",
	SkipWords: []string{"'", ",", "-", ".", "/", ";", "@", "[", "]", "environ", "er", "et", "le", "|", "à"},
	Simplifications: map[string]string{
		`(\d+)\s+h\s+(\d+)\s+min`: "$1h$2m",
		`(\d+)h(\d+)m?`:           "$1:$2",
		`cinq`:                    "5",
		`d'un`:                    "1",
		`d'une`:                   "1",
		`deux`:                    "2",
		`dix`:                     "10",
		`douze`:                   "12",
		`huit`:                    "8",
		`moins\s(?:de\s)?(\d+)\s?(minute|seconde|heure)`: "$1 $2",
		`moins\s(?:de\s)?(\d+)\s?h`:                      "$1 heure",
		`moins\s(?:de\s)?(\d+)\s?m`:                      "$1 minute",
		`moins\s(?:de\s)?(\d+)\s?s`:                      "$1 seconde",
		`neuf`:                                           "9",
		`onze`:                                           "11",
		`quatre`:                                         "4",
		`sept`:                                           "7",
		`six`:                                            "6",
		`trois`:                                          "3",
		`un`:                                             "1",
		`une`:                                            "1",
	},
	Translations: map[string]string{
		`janvier`:               "january",
		`janv`:                  "january",
		`février`:               "february",
		`févr`:                  "february",
		`mars`:                  "march",
		`avril`:                 "april",
		`avr`:                   "april",
		`mai`:                   "may",
		`juin`:                  "june",
		`juillet`:               "july",
		`juil`:                  "july",
		`août`:                  "august",
		`septembre`:             "september",
		`sept`:                  "september",
		`octobre`:               "october",
		`oct`:                   "october",
		`novembre`:              "november",
		`nov`:                   "november",
		`décembre`:              "december",
		`déc`:                   "december",
		`lundi`:                 "monday",
		`lun`:                   "monday",
		`mardi`:                 "tuesday",
		`mar`:                   "tuesday",
		`mercredi`:              "wednesday",
		`mer`:                   "wednesday",
		`jeudi`:                 "thursday",
		`jeu`:                   "thursday",
		`vendredi`:              "friday",
		`ven`:                   "friday",
		`samedi`:                "saturday",
		`sam`:                   "saturday",
		`dimanche`:              "sunday",
		`dim`:                   "sunday",
		`am`:                    "am",
		`pm`:                    "pm",
		`année`:                 "year",
		`an`:                    "year",
		`a`:                     "year",
		`mois`:                  "month",
		`m`:                     "month",
		`semaine`:               "week",
		`sem`:                   "week",
		`jour`:                  "day",
		`j`:                     "day",
		`heure`:                 "hour",
		`h`:                     "hour",
		`seconde`:               "second",
		`s`:                     "second",
		`l'année dernière`:      "1 year ago",
		`cette année`:           "0 year ago",
		`l'année prochaine`:     "in 1 year",
		`le mois dernier`:       "1 month ago",
		`ce mois-ci`:            "0 month ago",
		`le mois prochain`:      "in 1 month",
		`la semaine dernière`:   "1 week ago",
		`cette semaine`:         "0 week ago",
		`la semaine prochaine`:  "in 1 week",
		`hier`:                  "1 day ago",
		`aujourd'hui`:           "0 day ago",
		`demain`:                "in 1 day",
		`cette heure-ci`:        "0 hour ago",
		`cette minute-ci`:       "0 minute ago",
		`maintenant`:            "0 second ago",
		`dans (\d+) an`:         "in $1 year",
		`dans (\d+) ans`:        "in $1 year",
		`dans (\d+) a`:          "in $1 year",
		`il y a (\d+) an`:       "$1 year ago",
		`il y a (\d+) ans`:      "$1 year ago",
		`il y a (\d+) a`:        "$1 year ago",
		`dans (\d+) mois`:       "in $1 month",
		`dans (\d+) m`:          "in $1 month",
		`il y a (\d+) mois`:     "$1 month ago",
		`il y a (\d+) m`:        "$1 month ago",
		`dans (\d+) semaine`:    "in $1 week",
		`dans (\d+) semaines`:   "in $1 week",
		`dans (\d+) sem`:        "in $1 week",
		`il y a (\d+) semaine`:  "$1 week ago",
		`il y a (\d+) semaines`: "$1 week ago",
		`il y a (\d+) sem`:      "$1 week ago",
		`dans (\d+) jour`:       "in $1 day",
		`dans (\d+) jours`:      "in $1 day",
		`dans (\d+) j`:          "in $1 day",
		`il y a (\d+) jour`:     "$1 day ago",
		`il y a (\d+) jours`:    "$1 day ago",
		`il y a (\d+) j`:        "$1 day ago",
		`dans (\d+) heure`:      "in $1 hour",
		`dans (\d+) heures`:     "in $1 hour",
		`dans (\d+) h`:          "in $1 hour",
		`dans (\d+)h`:           "in $1 hour",
		`il y a (\d+) heure`:    "$1 hour ago",
		`il y a (\d+) heures`:   "$1 hour ago",
		`il y a (\d+) h`:        "$1 hour ago",
		`il y a (\d+)h`:         "$1 hour ago",
		`dans (\d+) minute`:     "in $1 minute",
		`dans (\d+) minutes`:    "in $1 minute",
		`dans (\d+) min`:        "in $1 minute",
		`dans (\d+) seconde`:    "in $1 second",
		`dans (\d+) secondes`:   "in $1 second",
		`dans (\d+) s`:          "in $1 second",
		`il y a (\d+) seconde`:  "$1 second ago",
		`il y a (\d+) secondes`: "$1 second ago",
		`il y a (\d+) s`:        "$1 second ago",
		`jan`:                   "january",
		`fév`:                   "february",
		`jun`:                   "june",
		`jul`:                   "july",
		`aoû`:                   "august",
		`sep`:                   "september",
		`lu`:                    "monday",
		`ma`:                    "tuesday",
		`me`:                    "wednesday",
		`je`:                    "thursday",
		`ve`:                    "friday",
		`sa`:                    "saturday",
		`di`:                    "sunday",
		`années`:                "year",
		`ans`:                   "year",
		`semaines`:              "week",
		`jours`:                 "day",
		`heures`:                "hour",
		`minutes`:               "minute",
		`secondes`:              "second",
		`dans`:                  "in",
		`en`:                    "in",
		`après`:                 "in",
		`il ya`:                 "ago",
		`il y a`:                "ago",
		`après-demain`:          "in 2 day",
		`avant-hier`:            "2 day ago",
	},
}

var fr_BE_Locale = LocaleData{
	Name:      "fr-BE",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_BF_Locale = LocaleData{
	Name:      "fr-BF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_BI_Locale = LocaleData{
	Name:      "fr-BI",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_BJ_Locale = LocaleData{
	Name:      "fr-BJ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_BL_Locale = LocaleData{
	Name:      "fr-BL",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CA_Locale = LocaleData{
	Name:      "fr-CA",
	Parent:    &fr_Locale,
	DateOrder: "YMD",
	Translations: map[string]string{
		`juill`: "july",
	},
}

var fr_CD_Locale = LocaleData{
	Name:      "fr-CD",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CF_Locale = LocaleData{
	Name:      "fr-CF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CG_Locale = LocaleData{
	Name:      "fr-CG",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CH_Locale = LocaleData{
	Name:      "fr-CH",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CI_Locale = LocaleData{
	Name:      "fr-CI",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CM_Locale = LocaleData{
	Name:      "fr-CM",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`matin`: "am",
		`mat`:   "am",
		`soir`:  "pm",
	},
}

var fr_DJ_Locale = LocaleData{
	Name:      "fr-DJ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_DZ_Locale = LocaleData{
	Name:      "fr-DZ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GA_Locale = LocaleData{
	Name:      "fr-GA",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GF_Locale = LocaleData{
	Name:      "fr-GF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GN_Locale = LocaleData{
	Name:      "fr-GN",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GP_Locale = LocaleData{
	Name:      "fr-GP",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GQ_Locale = LocaleData{
	Name:      "fr-GQ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_HT_Locale = LocaleData{
	Name:      "fr-HT",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`jr`:  "day",
		`hr`:  "hour",
		`sec`: "second",
	},
}

var fr_KM_Locale = LocaleData{
	Name:      "fr-KM",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_LU_Locale = LocaleData{
	Name:      "fr-LU",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MA_Locale = LocaleData{
	Name:      "fr-MA",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
	Translations: map[string]string{
		`jui`: "june",
	},
}

var fr_MC_Locale = LocaleData{
	Name:      "fr-MC",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MF_Locale = LocaleData{
	Name:      "fr-MF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MG_Locale = LocaleData{
	Name:      "fr-MG",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_ML_Locale = LocaleData{
	Name:      "fr-ML",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MQ_Locale = LocaleData{
	Name:      "fr-MQ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MR_Locale = LocaleData{
	Name:      "fr-MR",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MU_Locale = LocaleData{
	Name:      "fr-MU",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_NC_Locale = LocaleData{
	Name:      "fr-NC",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_NE_Locale = LocaleData{
	Name:      "fr-NE",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_PF_Locale = LocaleData{
	Name:      "fr-PF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_PM_Locale = LocaleData{
	Name:      "fr-PM",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_RE_Locale = LocaleData{
	Name:      "fr-RE",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_RW_Locale = LocaleData{
	Name:      "fr-RW",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_SC_Locale = LocaleData{
	Name:      "fr-SC",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_SN_Locale = LocaleData{
	Name:      "fr-SN",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_SY_Locale = LocaleData{
	Name:      "fr-SY",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_TD_Locale = LocaleData{
	Name:      "fr-TD",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_TG_Locale = LocaleData{
	Name:      "fr-TG",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_TN_Locale = LocaleData{
	Name:      "fr-TN",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_VU_Locale = LocaleData{
	Name:      "fr-VU",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_WF_Locale = LocaleData{
	Name:      "fr-WF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_YT_Locale = LocaleData{
	Name:      "fr-YT",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}
