// Code is generated by script; DO NOT EDIT.

package data

import "regexp"

var fr_Locale = LocaleData{
	Name:      "fr",
	DateOrder: "DMY",
	SkipWords: []string{"'", ",", "-", ".", "/", ";", "@", "[", "]", "environ", "er", "et", "le", "|", "à"},
	Simplifications: map[*regexp.Regexp]string{
		regexp.MustCompile(`(\A|\W|_)(\d+)\s+h\s+(\d+)\s+min(\z|\W|_)`):                        "${1}${2}h${3}m${4}",
		regexp.MustCompile(`(\A|\W|_)(\d+)h(\d+)m?(\z|\W|_)`):                                  "${1}${2}:${3}${4}",
		regexp.MustCompile(`(\A|\W|_)cinq(\z|\W|_)`):                                           "${1}5${2}",
		regexp.MustCompile(`(\A|\W|_)d'un(\z|\W|_)`):                                           "${1}1${2}",
		regexp.MustCompile(`(\A|\W|_)d'une(\z|\W|_)`):                                          "${1}1${2}",
		regexp.MustCompile(`(\A|\W|_)deux(\z|\W|_)`):                                           "${1}2${2}",
		regexp.MustCompile(`(\A|\W|_)dix(\z|\W|_)`):                                            "${1}10${2}",
		regexp.MustCompile(`(\A|\W|_)douze(\z|\W|_)`):                                          "${1}12${2}",
		regexp.MustCompile(`(\A|\W|_)huit(\z|\W|_)`):                                           "${1}8${2}",
		regexp.MustCompile(`(\A|\W|_)moins\s(?:de\s)?(\d+)\s?(minute|seconde|heure)(\z|\W|_)`): "${1}${2} ${3}${4}",
		regexp.MustCompile(`(\A|\W|_)moins\s(?:de\s)?(\d+)\s?h(\z|\W|_)`):                      "${1}${2} heure${3}",
		regexp.MustCompile(`(\A|\W|_)moins\s(?:de\s)?(\d+)\s?m(\z|\W|_)`):                      "${1}${2} minute${3}",
		regexp.MustCompile(`(\A|\W|_)moins\s(?:de\s)?(\d+)\s?s(\z|\W|_)`):                      "${1}${2} seconde${3}",
		regexp.MustCompile(`(\A|\W|_)neuf(\z|\W|_)`):                                           "${1}9${2}",
		regexp.MustCompile(`(\A|\W|_)onze(\z|\W|_)`):                                           "${1}11${2}",
		regexp.MustCompile(`(\A|\W|_)quatre(\z|\W|_)`):                                         "${1}4${2}",
		regexp.MustCompile(`(\A|\W|_)sept(\z|\W|_)`):                                           "${1}7${2}",
		regexp.MustCompile(`(\A|\W|_)six(\z|\W|_)`):                                            "${1}6${2}",
		regexp.MustCompile(`(\A|\W|_)trois(\z|\W|_)`):                                          "${1}3${2}",
		regexp.MustCompile(`(\A|\W|_)un(\z|\W|_)`):                                             "${1}1${2}",
		regexp.MustCompile(`(\A|\W|_)une(\z|\W|_)`):                                            "${1}1${2}",
	},
	Translations: []TranslationData{
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) secondes(\z|\W|_)`), "${1}${2} second ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) semaines(\z|\W|_)`), "${1}${2} week ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) seconde(\z|\W|_)`), "${1}${2} second ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) semaine(\z|\W|_)`), "${1}${2} week ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)la semaine prochaine(\z|\W|_)`), "${1}in 1 week${2}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) secondes(\z|\W|_)`), "${1}in ${2} second${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) semaines(\z|\W|_)`), "${1}in ${2} week${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) heures(\z|\W|_)`), "${1}${2} hour ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)la semaine dernière(\z|\W|_)`), "${1}1 week ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) minutes(\z|\W|_)`), "${1}in ${2} minute${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) seconde(\z|\W|_)`), "${1}in ${2} second${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) semaine(\z|\W|_)`), "${1}in ${2} week${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) heure(\z|\W|_)`), "${1}${2} hour ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) jours(\z|\W|_)`), "${1}${2} day ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) heures(\z|\W|_)`), "${1}in ${2} hour${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) minute(\z|\W|_)`), "${1}in ${2} minute${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) jour(\z|\W|_)`), "${1}${2} day ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) mois(\z|\W|_)`), "${1}${2} month ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)l'année prochaine(\z|\W|_)`), "${1}in 1 year${2}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) heure(\z|\W|_)`), "${1}in ${2} hour${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) jours(\z|\W|_)`), "${1}in ${2} day${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) ans(\z|\W|_)`), "${1}${2} year ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) sem(\z|\W|_)`), "${1}${2} week ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)l'année dernière(\z|\W|_)`), "${1}1 year ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)le mois prochain(\z|\W|_)`), "${1}in 1 month${2}"},
		{regexp.MustCompile(`(\A|\W|_)cette minute-ci(\z|\W|_)`), "${1}0 minute ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) jour(\z|\W|_)`), "${1}in ${2} day${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) mois(\z|\W|_)`), "${1}in ${2} month${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) an(\z|\W|_)`), "${1}${2} year ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)le mois dernier(\z|\W|_)`), "${1}1 month ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)cette heure-ci(\z|\W|_)`), "${1}0 hour ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) ans(\z|\W|_)`), "${1}in ${2} year${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) min(\z|\W|_)`), "${1}in ${2} minute${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) sem(\z|\W|_)`), "${1}in ${2} week${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) a(\z|\W|_)`), "${1}${2} year ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) h(\z|\W|_)`), "${1}${2} hour ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) j(\z|\W|_)`), "${1}${2} day ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) m(\z|\W|_)`), "${1}${2} month ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+) s(\z|\W|_)`), "${1}${2} second ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)cette semaine(\z|\W|_)`), "${1}0 week ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) an(\z|\W|_)`), "${1}in ${2} year${3}"},
		{regexp.MustCompile(`(\A|\W|_)il y a (\d+)h(\z|\W|_)`), "${1}${2} hour ago${3}"},
		{regexp.MustCompile(`(\A|\W|_)après-demain(\z|\W|_)`), "${1}in 2 day${2}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) a(\z|\W|_)`), "${1}in ${2} year${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) h(\z|\W|_)`), "${1}in ${2} hour${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) j(\z|\W|_)`), "${1}in ${2} day${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) m(\z|\W|_)`), "${1}in ${2} month${3}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+) s(\z|\W|_)`), "${1}in ${2} second${3}"},
		{regexp.MustCompile(`(\A|\W|_)aujourd'hui(\z|\W|_)`), "${1}0 day ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)cette année(\z|\W|_)`), "${1}0 year ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)dans (\d+)h(\z|\W|_)`), "${1}in ${2} hour${3}"},
		{regexp.MustCompile(`(\A|\W|_)avant-hier(\z|\W|_)`), "${1}2 day ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)ce mois-ci(\z|\W|_)`), "${1}0 month ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)maintenant(\z|\W|_)`), "${1}0 second ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)septembre(\z|\W|_)`), "${1}september${2}"},
		{regexp.MustCompile(`(\A|\W|_)dimanche(\z|\W|_)`), "${1}sunday${2}"},
		{regexp.MustCompile(`(\A|\W|_)décembre(\z|\W|_)`), "${1}december${2}"},
		{regexp.MustCompile(`(\A|\W|_)mercredi(\z|\W|_)`), "${1}wednesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)novembre(\z|\W|_)`), "${1}november${2}"},
		{regexp.MustCompile(`(\A|\W|_)secondes(\z|\W|_)`), "${1}second${2}"},
		{regexp.MustCompile(`(\A|\W|_)semaines(\z|\W|_)`), "${1}week${2}"},
		{regexp.MustCompile(`(\A|\W|_)vendredi(\z|\W|_)`), "${1}friday${2}"},
		{regexp.MustCompile(`(\A|\W|_)février(\z|\W|_)`), "${1}february${2}"},
		{regexp.MustCompile(`(\A|\W|_)janvier(\z|\W|_)`), "${1}january${2}"},
		{regexp.MustCompile(`(\A|\W|_)juillet(\z|\W|_)`), "${1}july${2}"},
		{regexp.MustCompile(`(\A|\W|_)minutes(\z|\W|_)`), "${1}minute${2}"},
		{regexp.MustCompile(`(\A|\W|_)octobre(\z|\W|_)`), "${1}october${2}"},
		{regexp.MustCompile(`(\A|\W|_)seconde(\z|\W|_)`), "${1}second${2}"},
		{regexp.MustCompile(`(\A|\W|_)semaine(\z|\W|_)`), "${1}week${2}"},
		{regexp.MustCompile(`(\A|\W|_)années(\z|\W|_)`), "${1}year${2}"},
		{regexp.MustCompile(`(\A|\W|_)demain(\z|\W|_)`), "${1}in 1 day${2}"},
		{regexp.MustCompile(`(\A|\W|_)heures(\z|\W|_)`), "${1}hour${2}"},
		{regexp.MustCompile(`(\A|\W|_)il y a(\z|\W|_)`), "${1}ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)samedi(\z|\W|_)`), "${1}saturday${2}"},
		{regexp.MustCompile(`(\A|\W|_)année(\z|\W|_)`), "${1}year${2}"},
		{regexp.MustCompile(`(\A|\W|_)après(\z|\W|_)`), "${1}in${2}"},
		{regexp.MustCompile(`(\A|\W|_)avril(\z|\W|_)`), "${1}april${2}"},
		{regexp.MustCompile(`(\A|\W|_)heure(\z|\W|_)`), "${1}hour${2}"},
		{regexp.MustCompile(`(\A|\W|_)il ya(\z|\W|_)`), "${1}ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)jeudi(\z|\W|_)`), "${1}thursday${2}"},
		{regexp.MustCompile(`(\A|\W|_)jours(\z|\W|_)`), "${1}day${2}"},
		{regexp.MustCompile(`(\A|\W|_)lundi(\z|\W|_)`), "${1}monday${2}"},
		{regexp.MustCompile(`(\A|\W|_)mardi(\z|\W|_)`), "${1}tuesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)août(\z|\W|_)`), "${1}august${2}"},
		{regexp.MustCompile(`(\A|\W|_)dans(\z|\W|_)`), "${1}in${2}"},
		{regexp.MustCompile(`(\A|\W|_)févr(\z|\W|_)`), "${1}february${2}"},
		{regexp.MustCompile(`(\A|\W|_)hier(\z|\W|_)`), "${1}1 day ago${2}"},
		{regexp.MustCompile(`(\A|\W|_)janv(\z|\W|_)`), "${1}january${2}"},
		{regexp.MustCompile(`(\A|\W|_)jour(\z|\W|_)`), "${1}day${2}"},
		{regexp.MustCompile(`(\A|\W|_)juil(\z|\W|_)`), "${1}july${2}"},
		{regexp.MustCompile(`(\A|\W|_)juin(\z|\W|_)`), "${1}june${2}"},
		{regexp.MustCompile(`(\A|\W|_)mars(\z|\W|_)`), "${1}march${2}"},
		{regexp.MustCompile(`(\A|\W|_)mois(\z|\W|_)`), "${1}month${2}"},
		{regexp.MustCompile(`(\A|\W|_)sept(\z|\W|_)`), "${1}september${2}"},
		{regexp.MustCompile(`(\A|\W|_)ans(\z|\W|_)`), "${1}year${2}"},
		{regexp.MustCompile(`(\A|\W|_)aoû(\z|\W|_)`), "${1}august${2}"},
		{regexp.MustCompile(`(\A|\W|_)avr(\z|\W|_)`), "${1}april${2}"},
		{regexp.MustCompile(`(\A|\W|_)dim(\z|\W|_)`), "${1}sunday${2}"},
		{regexp.MustCompile(`(\A|\W|_)déc(\z|\W|_)`), "${1}december${2}"},
		{regexp.MustCompile(`(\A|\W|_)fév(\z|\W|_)`), "${1}february${2}"},
		{regexp.MustCompile(`(\A|\W|_)jan(\z|\W|_)`), "${1}january${2}"},
		{regexp.MustCompile(`(\A|\W|_)jeu(\z|\W|_)`), "${1}thursday${2}"},
		{regexp.MustCompile(`(\A|\W|_)jul(\z|\W|_)`), "${1}july${2}"},
		{regexp.MustCompile(`(\A|\W|_)jun(\z|\W|_)`), "${1}june${2}"},
		{regexp.MustCompile(`(\A|\W|_)lun(\z|\W|_)`), "${1}monday${2}"},
		{regexp.MustCompile(`(\A|\W|_)mai(\z|\W|_)`), "${1}may${2}"},
		{regexp.MustCompile(`(\A|\W|_)mar(\z|\W|_)`), "${1}tuesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)mer(\z|\W|_)`), "${1}wednesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)nov(\z|\W|_)`), "${1}november${2}"},
		{regexp.MustCompile(`(\A|\W|_)oct(\z|\W|_)`), "${1}october${2}"},
		{regexp.MustCompile(`(\A|\W|_)sam(\z|\W|_)`), "${1}saturday${2}"},
		{regexp.MustCompile(`(\A|\W|_)sem(\z|\W|_)`), "${1}week${2}"},
		{regexp.MustCompile(`(\A|\W|_)sep(\z|\W|_)`), "${1}september${2}"},
		{regexp.MustCompile(`(\A|\W|_)ven(\z|\W|_)`), "${1}friday${2}"},
		{regexp.MustCompile(`(\A|\W|_)am(\z|\W|_)`), "${1}am${2}"},
		{regexp.MustCompile(`(\A|\W|_)an(\z|\W|_)`), "${1}year${2}"},
		{regexp.MustCompile(`(\A|\W|_)di(\z|\W|_)`), "${1}sunday${2}"},
		{regexp.MustCompile(`(\A|\W|_)en(\z|\W|_)`), "${1}in${2}"},
		{regexp.MustCompile(`(\A|\W|_)je(\z|\W|_)`), "${1}thursday${2}"},
		{regexp.MustCompile(`(\A|\W|_)lu(\z|\W|_)`), "${1}monday${2}"},
		{regexp.MustCompile(`(\A|\W|_)ma(\z|\W|_)`), "${1}tuesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)me(\z|\W|_)`), "${1}wednesday${2}"},
		{regexp.MustCompile(`(\A|\W|_)pm(\z|\W|_)`), "${1}pm${2}"},
		{regexp.MustCompile(`(\A|\W|_)sa(\z|\W|_)`), "${1}saturday${2}"},
		{regexp.MustCompile(`(\A|\W|_)ve(\z|\W|_)`), "${1}friday${2}"},
		{regexp.MustCompile(`(\A|\W|_)a(\z|\W|_)`), "${1}year${2}"},
		{regexp.MustCompile(`(\A|\W|_)h(\z|\W|_)`), "${1}hour${2}"},
		{regexp.MustCompile(`(\A|\W|_)j(\z|\W|_)`), "${1}day${2}"},
		{regexp.MustCompile(`(\A|\W|_)m(\z|\W|_)`), "${1}month${2}"},
		{regexp.MustCompile(`(\A|\W|_)s(\z|\W|_)`), "${1}second${2}"},
	},
}

var fr_BE_Locale = LocaleData{
	Name:      "fr-BE",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_BF_Locale = LocaleData{
	Name:      "fr-BF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_BI_Locale = LocaleData{
	Name:      "fr-BI",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_BJ_Locale = LocaleData{
	Name:      "fr-BJ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_BL_Locale = LocaleData{
	Name:      "fr-BL",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CA_Locale = LocaleData{
	Name:      "fr-CA",
	Parent:    &fr_Locale,
	DateOrder: "YMD",
	Translations: []TranslationData{
		{regexp.MustCompile(`(\A|\W|_)juill(\z|\W|_)`), "${1}july${2}"},
	},
}

var fr_CD_Locale = LocaleData{
	Name:      "fr-CD",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CF_Locale = LocaleData{
	Name:      "fr-CF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CG_Locale = LocaleData{
	Name:      "fr-CG",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CH_Locale = LocaleData{
	Name:      "fr-CH",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CI_Locale = LocaleData{
	Name:      "fr-CI",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_CM_Locale = LocaleData{
	Name:      "fr-CM",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
	Translations: []TranslationData{
		{regexp.MustCompile(`(\A|\W|_)matin(\z|\W|_)`), "${1}am${2}"},
		{regexp.MustCompile(`(\A|\W|_)soir(\z|\W|_)`), "${1}pm${2}"},
		{regexp.MustCompile(`(\A|\W|_)mat(\z|\W|_)`), "${1}am${2}"},
	},
}

var fr_DJ_Locale = LocaleData{
	Name:      "fr-DJ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_DZ_Locale = LocaleData{
	Name:      "fr-DZ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GA_Locale = LocaleData{
	Name:      "fr-GA",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GF_Locale = LocaleData{
	Name:      "fr-GF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GN_Locale = LocaleData{
	Name:      "fr-GN",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GP_Locale = LocaleData{
	Name:      "fr-GP",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_GQ_Locale = LocaleData{
	Name:      "fr-GQ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_HT_Locale = LocaleData{
	Name:      "fr-HT",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
	Translations: []TranslationData{
		{regexp.MustCompile(`(\A|\W|_)sec(\z|\W|_)`), "${1}second${2}"},
		{regexp.MustCompile(`(\A|\W|_)hr(\z|\W|_)`), "${1}hour${2}"},
		{regexp.MustCompile(`(\A|\W|_)jr(\z|\W|_)`), "${1}day${2}"},
	},
}

var fr_KM_Locale = LocaleData{
	Name:      "fr-KM",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_LU_Locale = LocaleData{
	Name:      "fr-LU",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MA_Locale = LocaleData{
	Name:      "fr-MA",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
	Translations: []TranslationData{
		{regexp.MustCompile(`(\A|\W|_)jui(\z|\W|_)`), "${1}june${2}"},
	},
}

var fr_MC_Locale = LocaleData{
	Name:      "fr-MC",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MF_Locale = LocaleData{
	Name:      "fr-MF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MG_Locale = LocaleData{
	Name:      "fr-MG",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_ML_Locale = LocaleData{
	Name:      "fr-ML",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MQ_Locale = LocaleData{
	Name:      "fr-MQ",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MR_Locale = LocaleData{
	Name:      "fr-MR",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_MU_Locale = LocaleData{
	Name:      "fr-MU",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_NC_Locale = LocaleData{
	Name:      "fr-NC",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_NE_Locale = LocaleData{
	Name:      "fr-NE",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_PF_Locale = LocaleData{
	Name:      "fr-PF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_PM_Locale = LocaleData{
	Name:      "fr-PM",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_RE_Locale = LocaleData{
	Name:      "fr-RE",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_RW_Locale = LocaleData{
	Name:      "fr-RW",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_SC_Locale = LocaleData{
	Name:      "fr-SC",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_SN_Locale = LocaleData{
	Name:      "fr-SN",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_SY_Locale = LocaleData{
	Name:      "fr-SY",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_TD_Locale = LocaleData{
	Name:      "fr-TD",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_TG_Locale = LocaleData{
	Name:      "fr-TG",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_TN_Locale = LocaleData{
	Name:      "fr-TN",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_VU_Locale = LocaleData{
	Name:      "fr-VU",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_WF_Locale = LocaleData{
	Name:      "fr-WF",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}

var fr_YT_Locale = LocaleData{
	Name:      "fr-YT",
	Parent:    &fr_Locale,
	DateOrder: "DMY",
}
