// Code is generated by script; DO NOT EDIT.

package data

var (
	ln_Locale    LocaleData
	ln_AO_Locale LocaleData
	ln_CF_Locale LocaleData
	ln_CG_Locale LocaleData
)

func init() {
	ln_Locale = merge(nil, LocaleData{
		Name:      "ln",
		DateOrder: "DMY",
		Charset:   []rune(`bcdefghiklnorstuvwxyzáâéíóúɔɛ́̌`),
		Translations: map[string][]string{
			"sanza ya zomi na mibale": {"december"},
			"sanza ya zomi na mɔkɔ":   {"november"},
			"mokɔlɔ mwa mibale":       {"tuesday"},
			"mokɔlɔ mwa misato":       {"wednesday"},
			"mokɔlɔ mwa yambo":        {"monday"},
			"mokɔlɔ ya mitano":        {"friday"},
			"mokɔlɔ ya minei":         {"thursday"},
			"sanza ya mibale":         {"february"},
			"sanza ya misato":         {"march"},
			"sanza ya mitano":         {"may"},
			"sanza ya motoba":         {"june"},
			"sanza ya mwambe":         {"august"},
			"sanza ya nsambo":         {"july"},
			"sanza ya libwa":          {"september"},
			"sanza ya minei":          {"april"},
			"sanza ya yambo":          {"january"},
			"sanza ya zomi":           {"october"},
			"sɛkɔndɛ":                 {"second"},
			"eyenga":                  {"sunday"},
			"mokɔlɔ":                  {"day"},
			"monuti":                  {"minute"},
			"mpokwa":                  {"pm"},
			"ngonga":                  {"hour"},
			"ntɔngɔ":                  {"am"},
			"mpɔsɔ":                   {"saturday"},
			"sanza":                   {"month"},
			"mobu":                    {"year"},
			"pɔsɔ":                    {"week"},
			"agt":                     {"august"},
			"apl":                     {"april"},
			"dsb":                     {"december"},
			"eye":                     {"sunday"},
			"fbl":                     {"february"},
			"gmt":                     {"gmt"},
			"mai":                     {"may"},
			"mbl":                     {"tuesday"},
			"min":                     {"thursday"},
			"mps":                     {"saturday"},
			"msi":                     {"march"},
			"mst":                     {"wednesday"},
			"mtn":                     {"friday"},
			"nvb":                     {"november"},
			"stb":                     {"september"},
			"utc":                     {"utc"},
			"yan":                     {"january"},
			"ybo":                     {"monday"},
			"yul":                     {"july"},
			"yun":                     {"june"},
			"ɔtb":                     {"october"},
			"am":                      {"am"},
			"pm":                      {"pm"},
			" ":                       {" "},
			"'":                       {""},
			"+":                       {"+"},
			",":                       {""},
			"-":                       {"-"},
			".":                       {"."},
			"/":                       {"/"},
			":":                       {":"},
			";":                       {""},
			"@":                       {""},
			"[":                       {""},
			"]":                       {""},
			"z":                       {"z"},
			"|":                       {""},
		},
		RelativeType: map[string]string{
			"this minute": "0 minute ago",
			"last month":  "1 month ago",
			"lobi ekoya":  "in 1 day",
			"lobi eleki":  "1 day ago",
			"next month":  "in 1 month",
			"this month":  "0 month ago",
			"last week":   "1 week ago",
			"last year":   "1 year ago",
			"next week":   "in 1 week",
			"next year":   "in 1 year",
			"this hour":   "0 hour ago",
			"this week":   "0 week ago",
			"this year":   "0 year ago",
			"lɛlɔ":        "0 day ago",
			"now":         "0 second ago",
		},
		KnownWords: []string{"sanza ya zomi na mibale", "sanza ya zomi na mɔkɔ", "mokɔlɔ mwa mibale", "mokɔlɔ mwa misato", "mokɔlɔ mwa yambo", "mokɔlɔ ya mitano", "mokɔlɔ ya minei", "sanza ya mibale", "sanza ya misato", "sanza ya mitano", "sanza ya motoba", "sanza ya mwambe", "sanza ya nsambo", "sanza ya libwa", "sanza ya minei", "sanza ya yambo", "sanza ya zomi", "this minute", "last month", "lobi ekoya", "lobi eleki", "next month", "this month", "last week", "last year", "next week", "next year", "this hour", "this week", "this year", "sɛkɔndɛ", "eyenga", "mokɔlɔ", "monuti", "mpokwa", "ngonga", "ntɔngɔ", "mpɔsɔ", "sanza", "lɛlɔ", "mobu", "pɔsɔ", "agt", "apl", "dsb", "eye", "fbl", "gmt", "mai", "mbl", "min", "mps", "msi", "mst", "mtn", "now", "nvb", "stb", "utc", "yan", "ybo", "yul", "yun", "ɔtb", "am", "pm", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "z", "|"},
	})

	ln_AO_Locale = merge(&ln_Locale, LocaleData{
		Name:      "ln-AO",
		DateOrder: "DMY",
	})

	ln_CF_Locale = merge(&ln_Locale, LocaleData{
		Name:      "ln-CF",
		DateOrder: "DMY",
	})

	ln_CG_Locale = merge(&ln_Locale, LocaleData{
		Name:      "ln-CG",
		DateOrder: "DMY",
	})
}
