// Code is generated by script; DO NOT EDIT.

package data

var (
	lrc_Locale    LocaleData
	lrc_IQ_Locale LocaleData
)

func init() {
	lrc_Locale = merge(nil, LocaleData{
		Name:      "lrc",
		DateOrder: "YMD",
		Charset:   []rune(`cdefghiklnorstuwxyzآأئاتثجدرزسشصفقلمنويٙپڤکگھیە`),
		Translations: map[string][]string{
			"سيپتامر": {"september"},
			"يوکتوڤر": {"october"},
			"جانڤیە":  {"january"},
			"ديسامر":  {"december"},
			"فيڤریە":  {"february"},
			"نوڤامر":  {"november"},
			"اڤریل":   {"april"},
			"اگوست":   {"august"},
			"ثانیە":   {"second"},
			"ديیقە":   {"minute"},
			"ھافتە":   {"week"},
			"جوان":    {"june"},
			"جولا":    {"july"},
			"ساات":    {"hour"},
			"مارس":    {"march"},
			"fri":     {"friday"},
			"gmt":     {"gmt"},
			"mon":     {"monday"},
			"sat":     {"saturday"},
			"sun":     {"sunday"},
			"thu":     {"thursday"},
			"tue":     {"tuesday"},
			"utc":     {"utc"},
			"wed":     {"wednesday"},
			"روز":     {"day"},
			"سال":     {"year"},
			"ميی":     {"may"},
			"am":      {"am"},
			"pm":      {"pm"},
			"ما":      {"month"},
			" ":       {" "},
			"'":       {""},
			"+":       {"+"},
			",":       {""},
			"-":       {"-"},
			".":       {"."},
			"/":       {"/"},
			":":       {":"},
			";":       {""},
			"@":       {""},
			"[":       {""},
			"]":       {""},
			"z":       {"z"},
			"|":       {""},
		},
		RelativeType: map[string]string{
			"this minute": "0 minute ago",
			"last month":  "1 month ago",
			"next month":  "in 1 month",
			"this month":  "0 month ago",
			"last week":   "1 week ago",
			"last year":   "1 year ago",
			"next week":   "in 1 week",
			"next year":   "in 1 year",
			"this hour":   "0 hour ago",
			"this week":   "0 week ago",
			"this year":   "0 year ago",
			"دیروز":       "1 day ago",
			"امرو":        "0 day ago",
			"شوصو":        "in 1 day",
			"now":         "0 second ago",
		},
		KnownWords: []string{"this minute", "last month", "next month", "this month", "last week", "last year", "next week", "next year", "this hour", "this week", "this year", "سيپتامر", "يوکتوڤر", "جانڤیە", "ديسامر", "فيڤریە", "نوڤامر", "اڤریل", "اگوست", "ثانیە", "ديیقە", "دیروز", "ھافتە", "امرو", "جوان", "جولا", "ساات", "شوصو", "مارس", "fri", "gmt", "mon", "now", "sat", "sun", "thu", "tue", "utc", "wed", "روز", "سال", "ميی", "am", "pm", "ما", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "z", "|"},
	})

	lrc_IQ_Locale = merge(&lrc_Locale, LocaleData{
		Name:      "lrc-IQ",
		DateOrder: "YMD",
	})
}
