// Code is generated by script; DO NOT EDIT.

package data

var (
	qu_Locale    LocaleData
	qu_BO_Locale LocaleData
	qu_EC_Locale LocaleData
)

func init() {
	qu_Locale = merge(nil, LocaleData{
		Name:      "qu",
		DateOrder: "DMY",
		Charset:   []rune(`bcdeghijklnorstuvwxyzáé`),
		Translations: map[string][]string{
			"pauqar waray": {"march"},
			"qhapaq sitwa": {"august"},
			"hatun puquy":  {"february"},
			"kapaq raymi":  {"december"},
			"qulla puquy":  {"january"},
			"anta sitwa":   {"july"},
			"inti raymi":   {"june"},
			"ayamarq'a":    {"november"},
			"miercoles":    {"wednesday"},
			"uma raymi":    {"september"},
			"kantaray":     {"october"},
			"aymuray":      {"may"},
			"domingo":      {"sunday"},
			"viernes":      {"friday"},
			"ayriwa":       {"april"},
			"jueves":       {"thursday"},
			"martes":       {"tuesday"},
			"minute":       {"minute"},
			"sabado":       {"saturday"},
			"second":       {"second"},
			"lunes":        {"monday"},
			"month":        {"month"},
			"hour":         {"hour"},
			"week":         {"week"},
			"year":         {"year"},
			"ant":          {"july"},
			"aya":          {"november"},
			"aym":          {"may"},
			"ayr":          {"april"},
			"day":          {"day"},
			"dom":          {"sunday"},
			"gmt":          {"gmt"},
			"hat":          {"february"},
			"int":          {"june"},
			"jue":          {"thursday"},
			"kan":          {"october"},
			"kap":          {"december"},
			"lun":          {"monday"},
			"mar":          {"tuesday"},
			"mie":          {"wednesday"},
			"pau":          {"march"},
			"qha":          {"august"},
			"qul":          {"january"},
			"sab":          {"saturday"},
			"uma":          {"september"},
			"utc":          {"utc"},
			"vie":          {"friday"},
			"am":           {"am"},
			"pm":           {"pm"},
			" ":            {" "},
			"'":            {""},
			"+":            {"+"},
			",":            {""},
			"-":            {"-"},
			".":            {"."},
			"/":            {"/"},
			":":            {":"},
			";":            {""},
			"@":            {""},
			"[":            {""},
			"]":            {""},
			"z":            {"z"},
			"|":            {""},
		},
		RelativeType: map[string]string{
			"this minute": "0 minute ago",
			"last month":  "1 month ago",
			"next month":  "in 1 month",
			"this month":  "0 month ago",
			"last week":   "1 week ago",
			"last year":   "1 year ago",
			"next week":   "in 1 week",
			"next year":   "in 1 year",
			"this hour":   "0 hour ago",
			"this week":   "0 week ago",
			"this year":   "0 year ago",
			"yesterday":   "1 day ago",
			"tomorrow":    "in 1 day",
			"today":       "0 day ago",
			"now":         "0 second ago",
		},
		KnownWords: []string{"pauqar waray", "qhapaq sitwa", "hatun puquy", "kapaq raymi", "qulla puquy", "this minute", "anta sitwa", "inti raymi", "last month", "next month", "this month", "ayamarq'a", "last week", "last year", "miercoles", "next week", "next year", "this hour", "this week", "this year", "uma raymi", "yesterday", "kantaray", "tomorrow", "aymuray", "domingo", "viernes", "ayriwa", "jueves", "martes", "minute", "sabado", "second", "lunes", "month", "today", "hour", "week", "year", "ant", "aya", "aym", "ayr", "day", "dom", "gmt", "hat", "int", "jue", "kan", "kap", "lun", "mar", "mie", "now", "pau", "qha", "qul", "sab", "uma", "utc", "vie", "am", "pm", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "z", "|"},
	})

	qu_BO_Locale = merge(&qu_Locale, LocaleData{
		Name:      "qu-BO",
		DateOrder: "DMY",
	})

	qu_EC_Locale = merge(&qu_Locale, LocaleData{
		Name:      "qu-EC",
		DateOrder: "DMY",
	})
}
