// Code is generated by script; DO NOT EDIT.

package data

var (
	so_Locale    LocaleData
	so_DJ_Locale LocaleData
	so_ET_Locale LocaleData
	so_KE_Locale LocaleData
)

func init() {
	so_Locale = merge(nil, LocaleData{
		Name:      "so",
		DateOrder: "DMY",
		Charset:   []rune(`bcdefghijklnorstuwxyz`),
		Translations: map[string][]string{
			"bisha laba iyo tobnaad": {"december"},
			"bisha kow iyo tobnaad":  {"november"},
			"bisha saddexaad":        {"march"},
			"bisha sagaalaad":        {"september"},
			"bisha sideedaad":        {"august"},
			"bisha todobaad":         {"july"},
			"bisha koobaad":          {"january"},
			"bisha shanaad":          {"may"},
			"bisha tobnaad":          {"october"},
			"bisha afraad":           {"april"},
			"bisha labaad":           {"february"},
			"bisha lixaad":           {"june"},
			"khamiis":                {"thursday"},
			"talaado":                {"tuesday"},
			"arbaco":                 {"wednesday"},
			"isniin":                 {"monday"},
			"minute":                 {"minute"},
			"second":                 {"second"},
			"jimco":                  {"friday"},
			"month":                  {"month"},
			"sabti":                  {"saturday"},
			"axad":                   {"sunday"},
			"hour":                   {"hour"},
			"week":                   {"week"},
			"year":                   {"year"},
			"afr":                    {"april"},
			"arb":                    {"wednesday"},
			"axd":                    {"sunday"},
			"day":                    {"day"},
			"gmt":                    {"gmt"},
			"isn":                    {"monday"},
			"jim":                    {"friday"},
			"kha":                    {"thursday"},
			"kit":                    {"november"},
			"kob":                    {"january"},
			"lab":                    {"february"},
			"lit":                    {"december"},
			"lix":                    {"june"},
			"sab":                    {"saturday"},
			"sad":                    {"march"},
			"sag":                    {"september"},
			"sha":                    {"may"},
			"sid":                    {"august"},
			"tal":                    {"tuesday"},
			"tob":                    {"october"},
			"tod":                    {"july"},
			"utc":                    {"utc"},
			"am":                     {"am"},
			"gn":                     {"pm"},
			"pm":                     {"pm"},
			"sn":                     {"am"},
			" ":                      {" "},
			"'":                      {""},
			"+":                      {"+"},
			",":                      {""},
			"-":                      {"-"},
			".":                      {"."},
			"/":                      {"/"},
			":":                      {":"},
			";":                      {""},
			"@":                      {""},
			"[":                      {""},
			"]":                      {""},
			"z":                      {"z"},
			"|":                      {""},
		},
		RelativeType: map[string]string{
			"this minute": "0 minute ago",
			"last month":  "1 month ago",
			"next month":  "in 1 month",
			"this month":  "0 month ago",
			"last week":   "1 week ago",
			"last year":   "1 year ago",
			"next week":   "in 1 week",
			"next year":   "in 1 year",
			"this hour":   "0 hour ago",
			"this week":   "0 week ago",
			"this year":   "0 year ago",
			"maanta":      "0 day ago",
			"shalay":      "1 day ago",
			"berri":       "in 1 day",
			"now":         "0 second ago",
		},
		KnownWords: []string{"bisha laba iyo tobnaad", "bisha kow iyo tobnaad", "bisha saddexaad", "bisha sagaalaad", "bisha sideedaad", "bisha todobaad", "bisha koobaad", "bisha shanaad", "bisha tobnaad", "bisha afraad", "bisha labaad", "bisha lixaad", "this minute", "last month", "next month", "this month", "last week", "last year", "next week", "next year", "this hour", "this week", "this year", "khamiis", "talaado", "arbaco", "isniin", "maanta", "minute", "second", "shalay", "berri", "jimco", "month", "sabti", "axad", "hour", "week", "year", "afr", "arb", "axd", "day", "gmt", "isn", "jim", "kha", "kit", "kob", "lab", "lit", "lix", "now", "sab", "sad", "sag", "sha", "sid", "tal", "tob", "tod", "utc", "am", "gn", "pm", "sn", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "z", "|"},
	})

	so_DJ_Locale = merge(&so_Locale, LocaleData{
		Name:      "so-DJ",
		DateOrder: "DMY",
	})

	so_ET_Locale = merge(&so_Locale, LocaleData{
		Name:      "so-ET",
		DateOrder: "DMY",
	})

	so_KE_Locale = merge(&so_Locale, LocaleData{
		Name:      "so-KE",
		DateOrder: "DMY",
	})
}
