// Code is generated by script; DO NOT EDIT.

package data

import "github.com/markusmobius/go-dateparser/internal/regexp"

var (
	sw_Locale    LocaleData
	sw_CD_Locale LocaleData
	sw_KE_Locale LocaleData
	sw_UG_Locale LocaleData
)

func init() {
	sw_Locale = merge(nil, LocaleData{
		Name:      "sw",
		DateOrder: "DMY",
		Charset:   []rune(`bcdefghijklnorstuvwyz`),
		Translations: map[string][]string{
			"alhamisi": {"thursday"},
			"februari": {"february"},
			"jumamosi": {"saturday"},
			"jumapili": {"sunday"},
			"jumatano": {"wednesday"},
			"jumatatu": {"monday"},
			"septemba": {"september"},
			"asubuhi":  {"am"},
			"desemba":  {"december"},
			"januari":  {"january"},
			"jumanne":  {"tuesday"},
			"novemba":  {"november"},
			"sekunde":  {"second"},
			"agosti":   {"august"},
			"aprili":   {"april"},
			"dakika":   {"minute"},
			"ijumaa":   {"friday"},
			"mchana":   {"pm"},
			"oktoba":   {"october"},
			"julai":    {"july"},
			"machi":    {"march"},
			"mwaka":    {"year"},
			"mwezi":    {"month"},
			"juni":     {"june"},
			"siku":     {"day"},
			"wiki":     {"week"},
			"ago":      {"august"},
			"apr":      {"april"},
			"dak":      {"minute"},
			"des":      {"december"},
			"feb":      {"february"},
			"gmt":      {"gmt"},
			"jan":      {"january"},
			"jul":      {"july"},
			"jun":      {"june"},
			"mac":      {"march"},
			"mei":      {"may"},
			"nov":      {"november"},
			"okt":      {"october"},
			"saa":      {"hour"},
			"sek":      {"second"},
			"sep":      {"september"},
			"utc":      {"utc"},
			"am":       {"am"},
			"pm":       {"pm"},
			" ":        {" "},
			"'":        {""},
			"+":        {"+"},
			",":        {""},
			"-":        {"-"},
			".":        {"."},
			"/":        {"/"},
			":":        {":"},
			";":        {""},
			"@":        {""},
			"[":        {""},
			"]":        {""},
			"z":        {"z"},
			"|":        {""},
		},
		RelativeType: map[string]string{
			"mwaka uliopita": "1 year ago",
			"mwezi uliopita": "1 month ago",
			"wiki iliyopita": "1 week ago",
			"dakika hii":     "0 minute ago",
			"mwaka ujao":     "in 1 year",
			"mwezi ujao":     "in 1 month",
			"wiki ijayo":     "in 1 week",
			"mwaka huu":      "0 year ago",
			"mwezi huu":      "0 month ago",
			"sasa hivi":      "0 second ago",
			"wiki hii":       "0 week ago",
			"saa hii":        "0 hour ago",
			"kesho":          "in 1 day",
			"jana":           "1 day ago",
			"leo":            "0 day ago",
		},
		RelativeTypeRegexes: []ReplacementData{
			{regexp.MustCompile(`(?i)sekunde (\d+[.,]?\d*) zilizopita`), "$1 second ago"},
			{regexp.MustCompile(`(?i)dakika (\d+[.,]?\d*) zilizopita`), "$1 minute ago"},
			{regexp.MustCompile(`(?i)sekunde (\d+[.,]?\d*) iliyopita`), "$1 second ago"},
			{regexp.MustCompile(`(?i)baada ya sekunde (\d+[.,]?\d*)`), "in $1 second"},
			{regexp.MustCompile(`(?i)dakika (\d+[.,]?\d*) iliyopita`), "$1 minute ago"},
			{regexp.MustCompile(`(?i)baada ya dakika (\d+[.,]?\d*)`), "in $1 minute"},
			{regexp.MustCompile(`(?i)miaka (\d+[.,]?\d*) iliyopita`), "$1 year ago"},
			{regexp.MustCompile(`(?i)miezi (\d+[.,]?\d*) iliyopita`), "$1 month ago"},
			{regexp.MustCompile(`(?i)siku (\d+[.,]?\d*) zilizopita`), "$1 day ago"},
			{regexp.MustCompile(`(?i)wiki (\d+[.,]?\d*) zilizopita`), "$1 week ago"},
			{regexp.MustCompile(`(?i)baada ya miaka (\d+[.,]?\d*)`), "in $1 year"},
			{regexp.MustCompile(`(?i)baada ya miezi (\d+[.,]?\d*)`), "in $1 month"},
			{regexp.MustCompile(`(?i)baada ya mwaka (\d+[.,]?\d*)`), "in $1 year"},
			{regexp.MustCompile(`(?i)baada ya mwezi (\d+[.,]?\d*)`), "in $1 month"},
			{regexp.MustCompile(`(?i)mwaka (\d+[.,]?\d*) uliopita`), "$1 year ago"},
			{regexp.MustCompile(`(?i)mwezi (\d+[.,]?\d*) uliopita`), "$1 month ago"},
			{regexp.MustCompile(`(?i)saa (\d+[.,]?\d*) zilizopita`), "$1 hour ago"},
			{regexp.MustCompile(`(?i)siku (\d+[.,]?\d*) iliyopita`), "$1 day ago"},
			{regexp.MustCompile(`(?i)wiki (\d+[.,]?\d*) iliyopita`), "$1 week ago"},
			{regexp.MustCompile(`(?i)baada ya siku (\d+[.,]?\d*)`), "in $1 day"},
			{regexp.MustCompile(`(?i)baada ya wiki (\d+[.,]?\d*)`), "in $1 week"},
			{regexp.MustCompile(`(?i)saa (\d+[.,]?\d*) iliyopita`), "$1 hour ago"},
			{regexp.MustCompile(`(?i)baada ya saa (\d+[.,]?\d*)`), "in $1 hour"},
		},
		RxCombined:      regexp.MustCompile(`(?i)(\A|[^\pL\pM\d]|_)(sekunde \d+[.,]?\d* zilizopita|dakika \d+[.,]?\d* zilizopita|sekunde \d+[.,]?\d* iliyopita|baada ya sekunde \d+[.,]?\d*|dakika \d+[.,]?\d* iliyopita|baada ya dakika \d+[.,]?\d*|miaka \d+[.,]?\d* iliyopita|miezi \d+[.,]?\d* iliyopita|siku \d+[.,]?\d* zilizopita|wiki \d+[.,]?\d* zilizopita|baada ya miaka \d+[.,]?\d*|baada ya miezi \d+[.,]?\d*|baada ya mwaka \d+[.,]?\d*|baada ya mwezi \d+[.,]?\d*|mwaka \d+[.,]?\d* uliopita|mwezi \d+[.,]?\d* uliopita|saa \d+[.,]?\d* zilizopita|siku \d+[.,]?\d* iliyopita|wiki \d+[.,]?\d* iliyopita|baada ya siku \d+[.,]?\d*|baada ya wiki \d+[.,]?\d*|saa \d+[.,]?\d* iliyopita|baada ya saa \d+[.,]?\d*)(\z|[^\pL\pM\d]|_)`),
		RxExactCombined: regexp.MustCompile(`(?i)^(sekunde \d+[.,]?\d* zilizopita|dakika \d+[.,]?\d* zilizopita|sekunde \d+[.,]?\d* iliyopita|baada ya sekunde \d+[.,]?\d*|dakika \d+[.,]?\d* iliyopita|baada ya dakika \d+[.,]?\d*|miaka \d+[.,]?\d* iliyopita|miezi \d+[.,]?\d* iliyopita|siku \d+[.,]?\d* zilizopita|wiki \d+[.,]?\d* zilizopita|baada ya miaka \d+[.,]?\d*|baada ya miezi \d+[.,]?\d*|baada ya mwaka \d+[.,]?\d*|baada ya mwezi \d+[.,]?\d*|mwaka \d+[.,]?\d* uliopita|mwezi \d+[.,]?\d* uliopita|saa \d+[.,]?\d* zilizopita|siku \d+[.,]?\d* iliyopita|wiki \d+[.,]?\d* iliyopita|baada ya siku \d+[.,]?\d*|baada ya wiki \d+[.,]?\d*|saa \d+[.,]?\d* iliyopita|baada ya saa \d+[.,]?\d*)$`),
		KnownWords:      []string{"mwaka uliopita", "mwezi uliopita", "wiki iliyopita", "dakika hii", "mwaka ujao", "mwezi ujao", "wiki ijayo", "mwaka huu", "mwezi huu", "sasa hivi", "alhamisi", "februari", "jumamosi", "jumapili", "jumatano", "jumatatu", "septemba", "wiki hii", "asubuhi", "desemba", "januari", "jumanne", "novemba", "saa hii", "sekunde", "agosti", "aprili", "dakika", "ijumaa", "mchana", "oktoba", "julai", "kesho", "machi", "mwaka", "mwezi", "jana", "juni", "siku", "wiki", "ago", "apr", "dak", "des", "feb", "gmt", "jan", "jul", "jun", "leo", "mac", "mei", "nov", "okt", "saa", "sek", "sep", "utc", "am", "pm", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "z", "|"},
	})

	sw_CD_Locale = merge(&sw_Locale, LocaleData{
		Name:      "sw-CD",
		DateOrder: "DMY",
		Translations: map[string][]string{
			"juma": {"week"},
		},
		KnownWords: []string{"mwaka uliopita", "mwezi uliopita", "wiki iliyopita", "dakika hii", "mwaka ujao", "mwezi ujao", "wiki ijayo", "mwaka huu", "mwezi huu", "sasa hivi", "alhamisi", "februari", "jumamosi", "jumapili", "jumatano", "jumatatu", "septemba", "wiki hii", "asubuhi", "desemba", "januari", "jumanne", "novemba", "saa hii", "sekunde", "agosti", "aprili", "dakika", "ijumaa", "mchana", "oktoba", "julai", "kesho", "machi", "mwaka", "mwezi", "jana", "juma", "juni", "siku", "wiki", "ago", "apr", "dak", "des", "feb", "gmt", "jan", "jul", "jun", "leo", "mac", "mei", "nov", "okt", "saa", "sek", "sep", "utc", "am", "pm", " ", "'", "+", ",", "-", ".", "/", ":", ";", "@", "[", "]", "z", "|"},
	})

	sw_KE_Locale = merge(&sw_Locale, LocaleData{
		Name:      "sw-KE",
		DateOrder: "DMY",
	})

	sw_UG_Locale = merge(&sw_Locale, LocaleData{
		Name:      "sw-UG",
		DateOrder: "DMY",
	})
}
