// Code is generated by script; DO NOT EDIT.

package data

import "regexp"

var teLocale = LocaleData{
	Name:                  "te",
	DateOrder:             "DMY",
	January:               []string{"జన", "జనవరి"},
	February:              []string{"ఫిబ్ర", "ఫిబ్రవరి"},
	March:                 []string{"మార్చి"},
	April:                 []string{"ఏప్రి", "ఏప్రిల్"},
	May:                   []string{"మే"},
	June:                  []string{"జూన్"},
	July:                  []string{"జులై"},
	August:                []string{"ఆగ", "ఆగస్టు"},
	September:             []string{"సెప్టెం", "సెప్టెంబర్"},
	October:               []string{"అక్టో", "అక్టోబర్"},
	November:              []string{"నవం", "నవంబర్"},
	December:              []string{"డిసెం", "డిసెంబర్"},
	Monday:                []string{"సోమ", "సోమవారం"},
	Tuesday:               []string{"మంగళ", "మంగళవారం"},
	Wednesday:             []string{"బుధ", "బుధవారం"},
	Thursday:              []string{"గురు", "గురువారం"},
	Friday:                []string{"శుక్ర", "శుక్రవారం"},
	Saturday:              []string{"శని", "శనివారం"},
	Sunday:                []string{"ఆది", "ఆదివారం"},
	AM:                    []string{"am"},
	PM:                    []string{"pm"},
	Year:                  []string{"సం", "సంవత్సరం"},
	Month:                 []string{"నె", "నెల"},
	Week:                  []string{"వా", "వారము"},
	Day:                   []string{"ది", "దినం"},
	Hour:                  []string{"గం", "గంట"},
	Minute:                []string{"ని", "నిమి", "నిమిషము"},
	Second:                []string{"సెక", "సెకను"},
	RelativeType: map[string][]string{
		`0 day ago`:    {`ఈ రోజు`},
		`0 hour ago`:   {`ఈ గంట`},
		`0 minute ago`: {`ఈ నిమిషం`},
		`0 month ago`:  {`ఈ నెల`},
		`0 second ago`: {`ప్రస్తుతం`},
		`0 week ago`:   {`ఈ వారం`},
		`0 year ago`:   {`ఈ సంవత్సరం`},
		`1 day ago`:    {`నిన్న`},
		`1 month ago`:  {`గత నెల`},
		`1 week ago`:   {`గత వారం`},
		`1 year ago`:   {`గత సంవత్సరం`},
		`in 1 day`:     {`రేపు`},
		`in 1 month`:   {`తదుపరి నెల`},
		`in 1 week`:    {`తదుపరి వారం`},
		`in 1 year`:    {`తదుపరి సంవత్సరం`},
	},
	RelativeTypeRegex: map[string][]*regexp.Regexp{
		`\1 day ago`: {
			regexp.MustCompile(`(?i)(\d+) రోజు క్రితం`),
			regexp.MustCompile(`(?i)(\d+) రోజుల క్రితం`),
		},
		`\1 hour ago`: {
			regexp.MustCompile(`(?i)(\d+) గం క్రితం`),
			regexp.MustCompile(`(?i)(\d+) గంట క్రితం`),
			regexp.MustCompile(`(?i)(\d+) గంటల క్రితం`),
		},
		`\1 minute ago`: {
			regexp.MustCompile(`(?i)(\d+) నిమి క్రితం`),
			regexp.MustCompile(`(?i)(\d+) నిమిషం క్రితం`),
			regexp.MustCompile(`(?i)(\d+) నిమిషాల క్రితం`),
		},
		`\1 month ago`: {
			regexp.MustCompile(`(?i)(\d+) నెల క్రితం`),
			regexp.MustCompile(`(?i)(\d+) నెలల క్రితం`),
		},
		`\1 second ago`: {
			regexp.MustCompile(`(?i)(\d+) సెక క్రితం`),
			regexp.MustCompile(`(?i)(\d+) సెకను క్రితం`),
			regexp.MustCompile(`(?i)(\d+) సెకన్ల క్రితం`),
		},
		`\1 week ago`: {
			regexp.MustCompile(`(?i)(\d+) వారం క్రితం`),
			regexp.MustCompile(`(?i)(\d+) వారాల క్రితం`),
		},
		`\1 year ago`: {
			regexp.MustCompile(`(?i)(\d+) సం క్రితం`),
			regexp.MustCompile(`(?i)(\d+) సంవత్సరం క్రితం`),
			regexp.MustCompile(`(?i)(\d+) సంవత్సరాల క్రితం`),
		},
		`in \1 day`: {
			regexp.MustCompile(`(?i)(\d+) రోజులో`),
			regexp.MustCompile(`(?i)(\d+) రోజుల్లో`),
		},
		`in \1 hour`: {
			regexp.MustCompile(`(?i)(\d+) గంటలో`),
			regexp.MustCompile(`(?i)(\d+) గంటల్లో`),
			regexp.MustCompile(`(?i)(\d+) గంలో`),
		},
		`in \1 minute`: {
			regexp.MustCompile(`(?i)(\d+) నిమిలో`),
			regexp.MustCompile(`(?i)(\d+) నిమిషంలో`),
			regexp.MustCompile(`(?i)(\d+) నిమిషాల్లో`),
		},
		`in \1 month`: {
			regexp.MustCompile(`(?i)(\d+) నెలలో`),
			regexp.MustCompile(`(?i)(\d+) నెలల్లో`),
		},
		`in \1 second`: {
			regexp.MustCompile(`(?i)(\d+) సెక లో`),
			regexp.MustCompile(`(?i)(\d+) సెకనులో`),
			regexp.MustCompile(`(?i)(\d+) సెకన్లలో`),
		},
		`in \1 week`: {
			regexp.MustCompile(`(?i)(\d+) వారంలో`),
			regexp.MustCompile(`(?i)(\d+) వారాల్లో`),
		},
		`in \1 year`: {
			regexp.MustCompile(`(?i)(\d+) సంలో`),
			regexp.MustCompile(`(?i)(\d+) సంవత్సరంలో`),
			regexp.MustCompile(`(?i)(\d+) సంవత్సరాల్లో`),
		},
	},
}
