// Code is generated by script; DO NOT EDIT.

package data

import "regexp"

var zu_Locale = LocaleData{
	Name:                  "zu",
	DateOrder:             "MDY",
	January:               []string{"jan", "januwari", "umasingana"},
	February:              []string{"feb", "februwari"},
	March:                 []string{"mas", "mashi"},
	April:                 []string{"eph", "ephreli"},
	May:                   []string{"mey", "meyi"},
	June:                  []string{"jun", "juni"},
	July:                  []string{"jul", "julayi"},
	August:                []string{"aga", "agasti"},
	September:             []string{"sep", "septhemba"},
	October:               []string{"okt", "okthoba"},
	November:              []string{"nov", "novemba"},
	December:              []string{"dis", "disemba"},
	Monday:                []string{"mso", "umsombuluko"},
	Tuesday:               []string{"bil", "ulwesibili"},
	Wednesday:             []string{"tha", "ulwesithathu"},
	Thursday:              []string{"sin", "ulwesine"},
	Friday:                []string{"hla", "ulwesihlanu"},
	Saturday:              []string{"mgq", "umgqibelo"},
	Sunday:                []string{"isonto", "son"},
	AM:                    []string{"am"},
	PM:                    []string{"pm"},
	Year:                  []string{"unyaka"},
	Month:                 []string{"inyanga"},
	Week:                  []string{"iviki"},
	Day:                   []string{"usuku"},
	Hour:                  []string{"ihora"},
	Minute:                []string{"iminithi"},
	Second:                []string{"isekhondi"},
	RelativeType: map[string][]string{
		`0 day ago`:    {`namhlanje`},
		`0 hour ago`:   {`leli hora`},
		`0 minute ago`: {`leli minithi`},
		`0 month ago`:  {`le nyanga`},
		`0 second ago`: {`manje`},
		`0 week ago`:   {`leli viki`},
		`0 year ago`:   {`kulo nyaka`},
		`1 day ago`:    {`izolo`},
		`1 month ago`:  {`inyanga edlule`},
		`1 week ago`:   {`iviki eledlule`},
		`1 year ago`:   {`onyakeni odlule`},
		`in 1 day`:     {`kusasa`},
		`in 1 month`:   {`inyanga ezayo`},
		`in 1 week`:    {`iviki elizayo`},
		`in 1 year`:    {`unyaka ozayo`},
	},
	RelativeTypeRegex: map[string][]*regexp.Regexp{
		`$1 day ago`: {
			regexp.MustCompile(`(?i)(\d+) izinsuku ezedlule`),
			regexp.MustCompile(`(?i)(\d+) usuku olwedlule`),
		},
		`$1 hour ago`: {
			regexp.MustCompile(`(?i)(\d+) amahora edlule`),
			regexp.MustCompile(`(?i)(\d+) ihora eledlule`),
		},
		`$1 minute ago`: {
			regexp.MustCompile(`(?i)(\d+) amaminithi edlule`),
			regexp.MustCompile(`(?i)(\d+) iminithi eledlule`),
		},
		`$1 month ago`: {
			regexp.MustCompile(`(?i)(\d+) inyanga edlule`),
			regexp.MustCompile(`(?i)(\d+) izinyanga ezedlule`),
		},
		`$1 second ago`: {
			regexp.MustCompile(`(?i)(\d+) amasekhondi edlule`),
			regexp.MustCompile(`(?i)(\d+) isekhondi eledlule`),
		},
		`$1 year ago`: {
			regexp.MustCompile(`(?i)(\d+) iminyaka edlule`),
			regexp.MustCompile(`(?i)(\d+) unyaka odlule`),
		},
	},
}
